### ISSUE TITLE
Bono doesn't SAS log rejected requests

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#1008]
When Bono rejects a request (e.g. because it's not authenticated and it's not a REGISTER), it sends SAS events for it, but doesn't send any markers and so the call can't be found.

Normally, the SAS markers would be applied in `UASTransaction::log_on_tsx_start`.  However, Bono can reject requests before this point.  In this case, `reject_request` in stateful_proxy.cpp is called instead, and that doesn't apply SAS markers.

**Comment by AlexHockey** [comment]
Crucially, it's the start and end time markers that don't exist - the start time marker is crucial for SAS to be able to display the trace.

**Comment by rkd-msw** [comment]
Fixed by the above PR.
