### ISSUE TITLE
Inter-sproutlet traffic should be logged in SAS

### ISSUE THREAD

**Issue by steelyvoid** [Metaswitch/sprout#1015]
Pull https://github.com/Metaswitch/sprout/pull/1004 added sprout logs at VERBOSE level for inter-sproutlet traffic, logging the serialized contents of requests and responses as they pass up and downstream from sproutlet to sproutlet (similar to the pre-existing RX/TX logs of serialised requests/responses already made for inter-node traffic)

Ideally, there should be some SAS logging of these inter-sproutlet messages.  It would be good if this could show the exact state of the message at this point (as opposed to a log that simply said "sending message from X to Y"), though this may be impractical for scale/performance reasons

**Comment by rkd-msw** [comment]
Discussed with @AlexHockey - we're currently going in the other direction, trying to cut back the amount we send to SAS, so we think we're unlikely to ever log full inter-Sproutlet messages to SAS.

We also now have high-level logs like "I-CSCF received an originating non-REGISTER request for ...", which will help show when processing moves to another Sproutlet, so I'm going to close this - we've effectively got as far as we can.
