### ISSUE TITLE
IPv6 is generally broken for the S-CSCF sproutlet

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/sprout#1029]
If the sprout_hostname is an IPv6 address then the S-CSCF plugin fails to load as the BGCF URI is invalid 

Debug scscfsproutlet.cpp:99:   BGCF URI           = sip:bgcf.[::1]:5054;transport=TCP
Error scscfsproutlet.cpp:125: Invalid BGCF URI sip:bgcf.[::1]:5054;transport=TCP

**Comment by eleanor-merry** [comment]
Similar to #929

**Comment by eleanor-merry** [comment]
A workaround to the above is to make the sprout_hostname a hostname. This then crashes on the S-CSCF node URI:

Debug scscfsproutlet.cpp:95: Creating S-CSCF Sproutlet
Debug scscfsproutlet.cpp:96:   S-CSCF cluster URI = sip:sprout.em4.cw-ngv.com:5054;transport=TCP
Debug scscfsproutlet.cpp:97:   S-CSCF node URI    = sip:::1:5054
Debug scscfsproutlet.cpp:98:   I-CSCF URI         = sip:sprout.em4.cw-ngv.com:5052;transport=TCP
Debug scscfsproutlet.cpp:99:   BGCF URI           = sip:bgcf.sprout.em4.cw-ngv.com:5054;transport=TCP
Error scscfsproutlet.cpp:117: Invalid S-CSCF node URI sip:::1:5054

This is built from the local_ip value in /etc/clearwater/config. We can't just wrap this in square brackets, as pj_getaddrinfo fails to parse this, e.g.:

Error stack.cpp:220: Failed to decode IP address [::1] (gethostbyname() has returned error (PJ_ERESOLVE))

Raising the priority as there's not a simple workaround

**Comment by bossmc** [comment]
Raising further to improve IPv6 support.

**Comment by rkd-msw** [comment]
Reopening - https://github.com/Metaswitch/sprout/commit/29f41eb451f86c12078cfb5e78ae66db87bef86a#diff-a3f32660e29268991e5b2bc959f00cfb partly undoes #1173, so you now have URIs like `sip:bgcf.[::1]` again.

**Comment by rkd-msw** [comment]
(This is particularly noticeable on an all-in-one node.)

**Comment by rkd-msw** [comment]
Returning to medium priority as this only happens when sprout_hostname is an IP address rather than a hostname (which I don't think we recommend, or default to anywhere, even on all-in-one nodes). I could even be convinced it was low priority.
