### ISSUE TITLE
Sprout requests to Homestead can take over a second

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/sprout#1090]
When running at medium load I'm finding that the poll_sprout_sip script restarts Sprout every 5 minutes or so. 

This is because the options poll is taking 2/3 seconds to be processed, so the monit poll times out. Sprout is congested because requests to homestead are taking a long time (>1sec). This is partly covered by https://github.com/Metaswitch/cpp-common/issues/132 (where requests don't get timed out).

This issue covers other problems with the Sprout->Homestead request. Sprout and Homestead don't agree on how long requests are taking - the Homestead stats report that the latency is 5 to 10 times smaller than Sprout does.

**Comment by mirw** [comment]
Network capture should answer the question of whether Sprout or Homestead is wrong pretty definitively (or whether it's actually network latency, although 1s is pretty unlikely!)

**Comment by JimBunch** [comment]
Marked as critical because Sprout is restarted every 5 minutes which is call processing service affecting.

**Comment by eleanor-merry** [comment]
(just to record this on the issue)
@JimBunch - you've agreed that your team will keep an eye out for this issue in their testing, and to close it if this issue isn't seen again

**Comment by tcaterisano** [comment]
Seems to be fixed in CCV9.
