### ISSUE TITLE
Sprout loops ACKs to itself after responding with 503 to an INVITE

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#1091]
After Sprout returns a 503 for an INVITE due to overload controls, it begins looping ACKs to itself until Max-Forwards has "expired". This additional processing triggers a LIR over the Cx for each ACK which adds to system latency, thereby "reinforcing" the overload condition (the overload was initially caused by Cx interface latency). A SAS trace has been collected.

**Comment by JimBunch** [comment]
Raising the priority to High since the system does not recover from the overload condition.

**Comment by matt-williams** [comment]
The set-up here is vm1.richlab.datcon.co.uk resolves to I-CSCF, sprout.vm1.richlab.datcon.co.uk resolves to S-CSCF.

The flow here is

*   Perimeta sends an INVITE (with request-URI vm1... and route sprout...).
*   Clearwater (S-CSCF) rejects it with a 503.
*   Perimeta sends an ACK (with request-URI vm1... and route sprout...).
*   Clearwater (S-CSCF) recognizes it as out-of-dialog and forwards it to vm1 (I-CSCF).
*   Clearwater (I-CSCF) does an LIR, finds the S-CSCF and forwards it (with request-uri vm1... and route sprout1...).
*   Clearwater (S-CSCF) recognizes it as out-of-dialog and forwards it to vm1 (I-CSCF).
*   ...

I think the key issue here is that we perform LIRs at all for ACKs - ACKs should either be in-dialog (in which case we follow the route-set) or hop-by-hop (to a negative INVITE).  If the I-CSCF receives an out-of-dialog ACK, I think it should reject it.  I need to check the specs to check that's correct.

There's an argument that we should apply overload processing to ACKs as well as other requests, but this is difficult - if we don't forward them, they'll just be resent, the call will eventually fail and they'll probably be retried - probably better to allow them to carry on.

**Comment by mirw** [comment]
I've coded a fix (https://github.com/Metaswitch/sprout/tree/iss1091), but not yet tested - I've been pulled to investigate another issue.

**Comment by rkd-msw** [comment]
I'll UT and possibly live test.

**Comment by rkd-msw** [comment]
I've had a go in UT and I'm not sure that your fix solves the issue. I'm concerned that:
* The ACK comes in, with the request line as `ACK sip:3196914123@homedomain:5060;transport=UDP SIP/2.0` and no Route headers
* No local Sproutlet owns the request, so we apply standard SIP proxying rules
* This means that it goes to homedomain:5060 - which is us again
* We're still in a loop

Do you agree? If so, I think the right fix is not to do standard proxying if the next hop URI matches PJUtils::is_home_domain or PJUtils::is_uri_local - we should just drop those requests with a log if no Sproutlet wants to handle them.

**Comment by rkd-msw** [comment]
(and I'm happy to make/test that fix if you agree with it)

**Comment by mirw** [comment]
As discussed, I'm surprised this wasn't fixed already - I thought we already had code in place not to default forward requests to ourselves.  The fix sounds sensible apart from that, though.

**Comment by mirw** [comment]
This also causes the following log spam:

   15-06-2015 15:42:57.525 UTC Warning scscfsproutlet.cpp:1634: Cannot determine charging role as no Route header, assume originating

**Comment by rkd-msw** [comment]
https://github.com/Metaswitch/sprout/commit/8e27f9bd09c0a436328e2fe4b2b174b7b437a708 fixed this in one case when first creating a UASTsx, but there's some similar code later without that check (https://github.com/Metaswitch/sprout/blob/1a4de016b5de472f3a80fe68fd9e379ae82e4b03/sprout/sproutletproxy.cpp#L791).

If I add this check, the I-CSCF drops ACKs, but it breaks one BGCF case (if we use ENUM and rewrite a request-URI to `sip:1234;npdi@homedomain`, we send that to the BGCF, which then has to forward a request to homedomain, and so fails this check.

I'm continuing to figure out a safe-but-sensible fix.

**Comment by rkd-msw** [comment]
@plfrancis, the fix in https://github.com/Metaswitch/sprout/issues/1099 should stop these ACKs from looping. Are you OK to test this?

**Comment by plfrancis** [comment]
The original scenario was reproduced in a recent overnight traffic run. Sprout turned around one ACK to itself, and the call was "aborted" gracefully. Closing.
