### ISSUE TITLE
After bypassing an unresponsive SIP AS, Sprout sends incomplete SIP messages

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#1109]
I sent a call through an AS that was not responding.  When Sprout determined this, it (correctly) bypassed it.  However, the forwarded message did not include all the SIP headers it should have - in particular, it was missing the Record-Route header.  This caused the call to fail in my test scenario, and would probably have caused billing (and other) errors if my test scenario had been different such that the call had been successfully set up.

This was because the SCSCFSproutlet goes back to the original request when it needs to bypass an AS (in `SCSCFSproutletTsx::on_rx_response` and `SCSCFSproutletTsx::on_timer_expiry`), but this skips over the initial processing done in the second branch of `SCSCFSproutletTsx::apply_originating_services`.

**Comment by bossmc** [comment]
Raising priority as this seems easy to hit in the real world and causes confusing SIP processing.
