### ISSUE TITLE
Assert in pjsip timer when connection fails to SIP peer.

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#1114]
See lots of log spam like the following when running stress.

```
25-06-2015 18:03:07.317 UTC Error pjsip: Assert failed: ../src/pj/timer.c:492 entry->_timer_id < 1
25-06-2015 18:03:07.317 UTC Error pjsip: tcpc0x7f85748f TCP connect() error: Connection refused [code=120111]
```

I suspect this is related to https://github.com/Metaswitch/pjsip-upstream/pull/35, but I can't really see how.  I suspect the next step will be to get the stack when we hit this.

**Comment by mirw** [comment]
Worth noting that we expect the connection to be failing - in the test, the peer had failed.  However, we shouldn't hit an assert as a result.

**Comment by bossmc** [comment]
Raising priority to resolve runtime crashes (even if the whole process doesn't go down, that thread will and we'll eventually run out of threads).  Also re-labelling to make the issue clear.

**Comment by AlexHockey** [comment]
Next step on this issue is to add more diags to allow us to debug it.

**Comment by steelyvoid** [comment]
Could the problem be at https://github.com/Metaswitch/pjsip-upstream/blob/master/pjsip/src/pjsip/sip_transport_tcp.c#L676?  We goto the error exit in this case, but we haven't set status to something other than PJ_SUCCESS, so this routine will destroy the tcp pointer (presumably freeing it up) but the caller thinks everything is OK and uses the pointer as normal.(and by the time we come to set the connection timer the memory could have been reused)

I imagine this is unlikely though - can't think its likely for that allocation to fail?

**Comment by mirw** [comment]
Yes, that sounds plausible but, as you say, unlikely - it looks like the only cause of failure is running out of memory (and the OOMkiller is likely to get involved before we actually fail a malloc).

**Comment by rkd-msw** [comment]
I've tried to reproduce this, but not had any success. Specifically, I've set a BGCF route to a nonexistent peer (one that doesn't respond to TCP SYNs and one that responds with a RST) and sent a request, but I don't see any `_timer_id` warnings:

```
10-08-2015 14:50:16.604 UTC Debug thread_dispatcher.cpp:199: Request latency = 849us
10-08-2015 14:50:18.604 UTC Verbose pjsip: tcpc0x7f21c40b TCP transport connect timeout timed out
10-08-2015 14:50:18.604 UTC Error pjsip: tcpc0x7f21c40b TCP connect() error: Operation timed out (PJ_ETIMEDOUT) [code=70009]
10-08-2015 14:50:18.604 UTC Warning pjsip: tsx0x7f21c40ba Failed to send Request msg INVITE/cseq=1 (tdta0x7f21c40b9cf0)! err=70009 (Operation timed out (PJ_ETIMEDOUT))
```

```
10-08-2015 14:59:41.849 UTC Debug basicproxy.cpp:2118: Starting timer C
10-08-2015 14:59:41.849 UTC Debug thread_dispatcher.cpp:193: Worker thread completed processing message 0x7f218803af78
10-08-2015 14:59:41.849 UTC Debug thread_dispatcher.cpp:199: Request latency = 821us
10-08-2015 14:59:41.849 UTC Error pjsip: tcpc0x7f218c03 TCP connect() error: Connection refused [code=120111]
10-08-2015 14:59:41.849 UTC Warning pjsip: tsx0x7f218c038 Failed to send Request msg INVITE/cseq=1 (tdta0x7f218c036ca0)! err=120111 (Connection refused)
10-08-2015 14:59:41.849 UTC Debug pjsip: tsx0x7f218c038 State changed from Calling to Terminated, event=TRANSPORT_ERROR
10-08-2015 14:59:41.849 UTC Debug basicproxy.cpp:212: tsx0x7f218c038d08 - tu_on_tsx_state UAC, TSX_STATE TRANSPORT_ERROR state=Terminated
10-08-2015 14:59:41.849 UTC Debug basicproxy.cpp:1797: tsx0x7f218c038d08 - uac_tsx = 0x7f218c094b10, uas_tsx = 0x7f218c008f70
10-08-2015 14:59:41.849 UTC Debug basicproxy.cpp:1805: TRANSPORT_ERROR event on current UAC transaction
10-08-2015 14:59:41.849 UTC Debug basicproxy.cpp:2130: Stopping timer C
```

```
[sprout-1]ubuntu@ec2-52-0-78-0:~$ grep _timer_id /var/log/sprout/sprout_current.txt
[sprout-1]ubuntu@ec2-52-0-78-0:~$
```

Matt, can you clarify what scenario you were running in when you hit this issue, so I can narrow down a minimal repro?

**Comment by mirw** [comment]
I'm pretty sure I was just running vanilla stress - this was around the time I was investigating performance changes between releases.  (I think the expected failures were because I was stopping nodes to patch/upgrade/debug them.)  Have you tried running stress?

**Comment by mirw** [comment]
I notice that our long-lived test systems haven't seen this recently.  We're not running stress over them, but they are hit reasonably hard.  So maybe this has been fixed by some other change?

**Comment by rkd-msw** [comment]
We've agreed to close this as it doesn't reproduce. The fix in https://github.com/Metaswitch/pjsip-upstream/issues/38 improves diagnostics here if it does reproduce - we'll see the timer duration and user-provided timer ID, allowing us to narrow down which timer is being double-scheduled.
