### ISSUE TITLE
SIP URIs with just npdi (and no other routing information) can loop pointlessly

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1121]
This is the case where:
* a SIP URI comes in (to example.com) as `sip:1234@example.com`
* ENUM rewrites it to `sip:1234;npdi@example.com` at the I-CSCF
* It immediately gets routed to the BGCF, which routes it back to example.com (I-CSCF)
* ENUM still rewrites it to `sip:1234;npdi@example.com`, and routes it to the BGCF
* etc. etc. until Max-Forwards decrements enough

I'm not sure if rewriting `sip:1234@example.com` to `sip:1234;npdi@example.com` is ever sensible, but we should handle this configuration better, not loop, and have the subscriber handled by the S-CSCF at some point.

**Comment by rkd-msw** [comment]
Discussed with @eleanor-merry  and @bossmc - fix is to not treat `npdi` as "routing information" in the TS 24.229 sense.

**Comment by bossmc** [comment]
Marking high priority since it blocks a high-priority issue.

**Comment by rkd-msw** [comment]
Fixed by #1156.
