### ISSUE TITLE
Calls longer that 1 minute are incomplete in SAS

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#1125]
If a call lasts more than 1 minute, any transactions that occur more than 1 minute into the call are missing from the SAS trace. This includes the BYE transaction when a party hangs up.

**Comment by AlexHockey** [comment]
I'm making this a medium as we have known about it for a while.

**Comment by rkd-msw** [comment]
This should be fixed with the latest SAS version.
