### ISSUE TITLE
401 responses from S-CSCF to I-CSCF only SAS logged on the receiving side. 

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#1142]
This screenshot demonstrates the problem. 
![image](https://cloud.githubusercontent.com/assets/4903205/8829824/b0e6422e-3090-11e5-935d-449cedf40ab7.png)

Easily reproducible with the live tests.

**Comment by AlexHockey** [comment]
I've assigned this as high priority as a) I've not seen it before so it is probably a regression and b) its quite visible and therefore likely to trigger questions from users.

**Comment by rkd-msw** [comment]
I suspect we should be calling `set_trail` on `tsx` at https://github.com/Metaswitch/sprout/blob/dev/sprout/authentication.cpp#L926.
