### ISSUE TITLE
Can't retrieve any SNMP registration statistics

### ISSUE THREAD

**Issue by dcollins991** [Metaswitch/sprout#1163]
Ran several SIP Digest registration tests and then queried the snmp stats using:
`snmpget -v2c -c clearwater -O f 192.168.159.168 sproutInitialRegistrationAttempts`
Response:
`.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable.sproutInitialRegistrationEntry.sproutInitialRegistrationAttempts = No Such Object available on this agent at this OID`
I performed similar tests on the some of the other stats (sproutInitialRegistrationSuccesses, sproutSIPDigestAuthenticationAttempts, sproutAKAAuthenticationAttempts).  I was never able to retrieve any counts.
This is on V8 Jane Eyre release.

**Comment by rkd-msw** [comment]
That's as expected - there are no values at the sproutInitialRegistrationAttempts OID, they're one level down (at the 5-second/5-minute scope OIDs).

Can you confirm whether:
`snmpwalk -v2c -c clearwater -O f <ip> sproutInitialRegistrationAttempts`

or

`snmptable -v2c -c clearwater -Ci -O f <ip> sproutInitialRegistrationTable`

give the expected results?

If not, can you upload a diags bundle? If those work, can you pass it back so we can think about docs clarifications?

**Comment by dcollins991** [comment]
snmpwalk -v2c -c clearwater -O f 192.168.159.168 sproutInitialRegistrationAttempts
.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable.sproutInitialRegistrationEntry.sproutInitialRegistrationAttempts = No Such Object available on this agent at this OID

snmptable -v2c -c clearwater -O f 192.168.159.168 sproutInitialRegistrationTable
.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable: No entries


So, both commands fail.  Will gather the diags bundle and upload.

**Comment by mirw** [comment]
This definitely works for me on the latest code.  It might be worth retrying on the King Lear release before we spend too long digging through diagnostics - please can you try that?

**Comment by dcollins991** [comment]
OK.  will install and let you know.

**Comment by dcollins991** [comment]
The snmptable command now works as,
snmptable -v2c -c clearwater -O f 192.168.159.168 sproutInitialRegistrationTable
SNMP table: .iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable

 sproutInitialRegistrationAttempts sproutInitialRegistrationSuccesses sproutInitialRegistrationFailures
                                 0                                  0                                 0
                                 2                                  2                                 0
                                 0                                  0                                 0
The snmpwalk command works by specifying the table entry again.  
snmpwalk -v2c -c clearwater -O f 192.168.159.168 sproutInitialRegistrationTable (result not included as it was lengthy).
But, the command, 
 snmpwalk -v2c -c clearwater -O f 192.168.159.169 sproutInitialRegistrationAttempts
.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable.sproutInitialRegistrationEntry.sproutInitialRegistrationAttempts = No Such Object available on this agent at this OID
does not.  Do you expect it to work?

**Comment by rkd-msw** [comment]
I would expect it to work (and saw it working a few minutes ago). I note that you're specifying a different IP address in the failing command (192.168.159.169 vs. 192.168.159.168) - could that be the issue?

**Comment by dcollins991** [comment]
Good spot!  I should have checked both mates.
snmpwalk -v2c -c clearwater -O f 192.168.159.168 sproutInitialRegistrationAttempts
.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable.sproutInitialRegistrationEntry.sproutInitialRegistrationAttempts.scopePrevious5SecondPeriod = Gauge32: 0
.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable.sproutInitialRegistrationEntry.sproutInitialRegistrationAttempts.scopeCurrent5MinutePeriod = Gauge32: 0
.iso.memberBody.gb.gbNational.gbNatCompany.dataConnection.projectClearwater.sprout.sproutInitialRegistrationTable.sproutInitialRegistrationEntry.sproutInitialRegistrationAttempts.scopePrevious5MinutePeriod = Gauge32: 0

I guess this can be closed now.  The problem is only in the Jane Eyre load.

**Comment by rkd-msw** [comment]
We should update the documentation with some example commands - SNMP is tricky to use and I think an example query and expected response would be helpful, particularly given the focus we're now putting on stats.

**Comment by rkd-msw** [comment]
Alan, as a relatively low-priority task, can you think about how to update our SNMP docs to make the correct usage clearer (e.g. so that users don't try an `snmpget` on `sproutInitialRegistrationAttempts`?).

**Comment by alango** [comment]
Fixed by clearwater-readthedocs 100
