### ISSUE TITLE
Statistics sproutInitialRegistrationAttempts, sproutInitialRegistrationFailures Don't work in SIP Digest Register Fail

### ISSUE THREAD

**Issue by dcollins991** [Metaswitch/sprout#1169]
I have a test scenario in which a SIP Digest attempt is made with an invalid password.  For this expected register failure case, neither sproutInitialRegistrationFailures nor sproutInitialRegistrationAttempts is changed.  However, sproutSIPDigestAuthenticationFailures does change.

```
The summary for the test results are:
Scenario: SIP Digest registration failure
Registration stats
            sproutInitialRegistrationAttempts Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
        sproutSIPDigestAuthenticationAttempts Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
           sproutInitialRegistrationSuccesses Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Passed
            sproutInitialRegistrationFailures Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
       sproutSIPDigestAuthenticationSuccesses Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Passed
        sproutSIPDigestAuthenticationFailures Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
```

**Comment by mirw** [comment]
@rkd-msw, please can you (or @alango) take a look?  I suspect this might nominally be WAS, although maybe the spec is wrong?

**Comment by dcollins991** [comment]
Please check the failure path also for re-registrations and de-registrations.  I get similar issues for these counters.  See the regression test summary results as:
Scenario: SIP Digest registration, re-registration with bad password, de-registration
Registration stats
            sproutInitialRegistrationAttempts Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed
        sproutSIPDigestAuthenticationAttempts Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
           sproutInitialRegistrationSuccesses Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed
       sproutSIPDigestAuthenticationSuccesses Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
Re-Registration stats
                 sproutReRegistrationAttempts Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
        sproutSIPDigestAuthenticationAttempts Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
                sproutReRegistrationSuccesses Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Passed
                 sproutReRegistrationFailures Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
       sproutSIPDigestAuthenticationSuccesses Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Passed
        sproutSIPDigestAuthenticationFailures Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
De-Registration stats
                 sproutDeRegistrationAttempts Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
                sproutDeRegistrationSuccesses Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed

Scenario: SIP Digest registration, re-registration, de-registration fail
Registration stats
            sproutInitialRegistrationAttempts Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed
        sproutSIPDigestAuthenticationAttempts Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
           sproutInitialRegistrationSuccesses Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed
       sproutSIPDigestAuthenticationSuccesses Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
Re-Registration stats
                 sproutReRegistrationAttempts Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
        sproutSIPDigestAuthenticationAttempts Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed
                sproutReRegistrationSuccesses Prev5Sec: 0 Curr5Minute: 1 Prev5Minute: 0 Passed
       sproutSIPDigestAuthenticationSuccesses Prev5Sec: 1 Curr5Minute: 1 Prev5Minute: 0 Passed
De-Registration stats
                 sproutDeRegistrationAttempts Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed
                sproutDeRegistrationSuccesses Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Passed
                 sproutDeRegistrationFailures Prev5Sec: 0 Curr5Minute: 0 Prev5Minute: 0 Failed

**Comment by rkd-msw** [comment]
I discussed with Matt and we think this is the right behaviour:

  - we don't know if a REGISTER that fails authentication is a initial registration or a re-registration, as we haven't queried the bindings in memcached
  - we don't really want to add that processing in for failed REGISTERs just to update a stat
  - users can just sum the two stats (REGISTERs that failed due to authentication + REGISTERs that failed for other reasons) if the overall view is needed

Alan, could you update (and probably recirculate) the spec to make this clear, and then update the docs?
