### ISSUE TITLE
Sprout crash when routing a tel: URI with strict routing

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1170]
I sent the following request into Sprout:

```
INVITE tel:+1234 SIP/2.0^M
Via: SIP/2.0/TCP 10.0.132.202:5060;branch=z9hG4bK-20409-1-0^M
From: sipp <sip:sipp@10.0.132.202:5060>;tag=20409SIPpTag001^M
To: <tel:+1234>^M
Route: <sip:icscf@10.0.132.202:5052;transport=tcp>^M
Route: <sip:icscf@homer.staging.cw-ngv.com:5052;transport=tcp>^M
Call-ID: 1-20409@10.0.132.202^M
CSeq: 1 INVITE^M
Contact: sip:sipp@10.0.132.202:5060^M
Max-Forwards: 70^M
Subject: Performance Test^M
```

Following normal I-CSCF routing rules, it tried to just send it on to `sip:icscf@homer.staging.cw-ngv.com:5052;transport=tcp`. Because we don't specify `lr`, it tried to put `tel:+1234` in the Route header. While serialising that Route header, it tried to interpret the URI as a SIP URI, and segfaulted.

**Comment by rkd-msw** [comment]
Specifically, it crashes at https://github.com/Metaswitch/pjsip-upstream/blob/fe5f03394a7ab70059f8e91144fe5dba86486261/pjsip/src/pjsip/sip_msg.c#L1837.

**Comment by JimBunch** [comment]
Marking as critical since it is service affecting.

**Comment by mirw** [comment]
I had a suspicion that TEL URIs shouldn't be allowed in Route headers, but I can't find anything that says this.  It actually looks as though the PJSIP code is designed to support any URI - it's just a check for a proprietary SIP URI parameter that's causing us to barf.  I think we should either remove that check (we never use it, and probably shouldn't) or wrap it in an "if (SIP URI)" - the parameter isn't valid on TEL URIs.
