### ISSUE TITLE
sometimes the features.d directory gets polluted with Debian package files (*.dpkg-*)

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1174]
I this happens when installing and there's already a file of the same name in the features.d directory and you answer Y to the following question:
```
Configuration file '/etc/clearwater/features.d/metaswitch-core-sprout'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** metaswitch-core-sprout (Y/I/N/O/D/Z) [default=N] ? Y
```
In this case, the /etc/features.d directory will look like this:
```
drwxr-xr-x 2 root root 4096 Aug 14 10:37 .
drwxr-xr-x 8 root root 4096 Aug 12 14:28 ..
-rw-r--r-- 1 root root  120 Oct 14  2014 metaswitch-core-sprout
-rw-r--r-- 1 root root  129 Aug 14 10:33 metaswitch-core-sprout.dpkg-old
```
This will in turn cause problems when processing the features.d directory, since all files are blindly sourced. As such, I've changed all the init.d scripts like this:
```
-          for file in $(find /etc/clearwater/features.d -type f)
+          for file in $(find /etc/clearwater/features.d -type f \! -name '*.dpkg-*')
```
BTW - This is not just a sprout problem, but a problem for all services that process the features.d directory.

**Comment by mirw** [comment]
The `/etc/clearwater/features.d/metaswitch-core-sprout` should either be always created by the user or always created by a package.  That isn't happening here, and that's what causing the question - I think that's the bug.  It looks here as though the file has either

*   been created by a user and then overwritten by a package or
*   been created by a package, modified by a user and then overwritten (back to its original value) by a package.

@dtheobald, please can you look at

*   what should be creating the file - is it a user or is it a package
*   whether a user should ever edit the file?

Note that if a package is being installed automatically (e.g. by an orchestrator) there's no way for the user to enter their preference for preserving or replacing the configuration file.

**Comment by dtheobald** [comment]
With CC this can occur when upgrading in place since we preserve configuration, which includes those features.d files. This problem was most annoying, back in the day, when homestead-prov was turned on by setting LOCAL_PROVISIONING_ENABLED=Y in a features.d file. As such, when we would upgrade in place and keep our edited configuration, the init.d script would also read the .dpkg-old files and whichever one was alphabetically last would win.

**Comment by mirw** [comment]
Should the features.d files ever be edited by users?

I think homestead-prov should be enabled by `LOCAL_PROVISIONING_ENABLED=Y` being set in the features.d file in the package itself.

Likewise, I think `ENUM_FILE_ENABLED=Y` (or whatever it was) should be set in the features.d file in the sprout package.

**Comment by dtheobald** [comment]
I don't know if (currently) there are any settings that should be edited by a user. I only know that there used to be, which is what prompted my change many moons ago.

**Comment by mirw** [comment]
My suggestion is that in future, either

*   the package should be updated to define the features.d entries correctly or
*   the package's install script should not include the features.d file itself but should write it as part of the install process if it doesn't exist already.

What do you think?

**Comment by dtheobald** [comment]
That sounds reasonable to me.

**Comment by mirw** [comment]
Thanks!  I think that means we don't need to change this and can close the issue - do you agree?

**Comment by dtheobald** [comment]
Yes
