### ISSUE TITLE
Error in updating the shared configuration !

### ISSUE THREAD

**Issue by pbauskar** [Metaswitch/sprout#1183]
Hi 

I edit the file (multiple times) "/etc/clearwater/shared_config", and then executed "upload_shared_config" as instructed. In the response, i'm getting error - {"message":"Internal Server Error"}.

root@ralf:/home/ralfellis# vi /etc/clearwater/shared_config
root@ralf:/home/ralfellis# /usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
Upload shared configuration failed to http://10.5.123.66:4000/v2/keys/clearwater/site1/configuration/shared_config
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   851  100    35  100   816      5    135  0:00:07  0:00:06  0:00:01     0
{"message":"Internal Server Error"}root@ralf:/home/ralfellis# 

Can you please help? Below are the contents of the shared_config file.

# Deployment definition
home_domain=testims.com
sprout_hostname=sprout.testims.com
#hs_hostname=homestead.testims.com:8888
hs_hostname=hs.testims.com:8888
#hs_provisioning_hostname=homestead.testims.com:8889
hs_provisioning_hostname=hs.testims.com:8889
ralf_hostname=ralf.testims.com:10888
xdms_hostname=homer.testims.com:7888

# Email server configuration
smtp_smarthost=
smtp_username=
smtp_password=
email_recovery_sender=

# Keys
signup_key="ims"
turn_workaround="ims"
ellis_api_key="ims"
ellis_cookie_key="ims"

# Enable I-CSCF and S-CSCF
icscf=5052
upstream_hostname=sprout
upstream_port=5052

# Application Servers
memento_enabled='Y'

**Comment by mirw** [comment]
@eleanor-merry, are you best-placed to look at this, or is @rkd-msw?

**Comment by eleanor-merry** [comment]
Hi @pbauskar. Is etcd running on your node? Is the etcd cluster as a whole healthy? Can you please upload the /var/log/clearwater-etcd/clearwater-etcd.log (either as a gist - https://gist.github.com, or you can email them to us on our mailing list - http://www.projectclearwater.org/community/)

Thanks

**Comment by pbauskar** [comment]
Hi

Unfortunately I dismantled the setup and created a setup with no Cluster (manual configuration without “etcd”).

I’m sorry.

Thanks and regards

Prashant Bauskar | NDU | Tech Mahindra
Sharda Center, Pune 411 004, INDIA
• Office: +91 20 41001000| Ext - 1771| Mobile: +91 9960606625
Email: bauskar@techmahindra.com<mailto:bauskar@techmahindra.com>
www.techmahindra.com<http://www.techmahindra.com/>

[Description: cid:image001.jpg@01CE7656.B7A238D0]<http://www.techmahindra.com/>

Follow Tech Mahindra here!
[Description: Facebook]<http://www.facebook.com/TechMahindra>[Description: Twitter]<http://twitter.com/Tech_Mahindra>[Description: Linked In]<http://www.linkedin.com/company/tech-mahindra>

**Comment by eleanor-merry** [comment]
Closing as we've recently changed the etcd code, and without diagnostics we can't take this issue any further.
