### ISSUE TITLE
Unit test time - a test that controls current time doesn't clean up

### ISSUE THREAD

**Issue by chriscoomber** [Metaswitch/sprout#1185]
Background: We've added a custom module to sprout, and one the UTs for this module involves testing the time.

Issue: I was confused by the fact that "time_t now = time(nullptr)"; was returning a time of 1 hour in the future (as in, the "seconds since the epoch" was 3600 too high).

Detail: It's possible this was caused by another UT (sprout's or a module's) earlier calling into cwtest_completely_control_time() or cwtest_advance_time_ms() without subsequently calling cwtest_reset_time(). I confirmed this by running cwtest_reset_time() at the top of my UT and it fixed my problem. (More detail: I was running `cd sprout; make test`, and my UT runs between MangelwurzelTest and AlarmTest.)

Impact: The impact is "I was confused" and new UTs will need to reset time at the start for safety, but UTs should clean up after themselves, so this is an issue of some UT somewhere - I haven't dug around to see which UT is to blame.

**Comment by AME2** [comment]
Fixed by these pull requests:
https://github.com/Metaswitch/sprout/pull/1307
https://github.com/Metaswitch/cpp-common/pull/448
