### ISSUE TITLE
Sprout does not generate EVENT ACRs for some failed REGISTERs.

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#1193]
Spotted by code reading. There are a bunch of places where `process_register_request` rejects a request but doesn't send an ACR. Table 5.2.1.1 of [32.260](http://www.3gpp.org/DynaReport/32260.htm) says we should.

**Comment by AlexHockey** [comment]
The error conditions that cause a REGISTER to be rejected without an ACR are:

* Homestead error / overload
* HSS error / overload
* Memcached error.
* Certain semantically invalid requests.
* Attempt to deregister an emergency registration.

**Comment by JimBunch** [comment]
Marked as critical since it affects the accuracy of the billing.

**Comment by AlexHockey** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/1350
