### ISSUE TITLE
Sprout's implementation `Session-expires` and `Min-SE` headers does not match RFC 4028

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#1194]
Sprout's current handling of session expires is doesn't match RFC4028 very closely, which has a variety of consequences. For example:

* Sprout never does any session-expires processing on the response, which means if the UAS does not support RFC 4028 we never ask the UAC to handle session refresh. 
* Sprout refuses to reduce a session-expires (even though it allowed to) and rejects the request instead.
* When sprout sees a request with both session-expires and min-se, it slams the session-expires down to equal the min-se, for no discernible reason whatsoever.
* When sprout realizes it cannot set the session-expires it wants, it rejects the request. This is not allowed if the UAC does not support session timers. Even if session-timers are supported, sprout uses the wrong error code which means the UAC does not know that it might be able to submit a different request that is acceptable. 

Raising this as one issue since I'd imagine we'd fix all of these problems at once.

**Comment by mirw** [comment]
Also, our description of RFC 4028 support in http://clearwater.readthedocs.org/en/latest/SIP_Interface_Specifications/index.html is out-of-date.  We should fix that too (once we've addressed the above).

**Comment by AlexHockey** [comment]
Fixed by #1205, but keeping the issue until I merge the docs update.
