### ISSUE TITLE
HSS deregisters due to Chronos timer pops are not logged to SAS

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/sprout#1201]
This is because we don't pass the trail ID to the HTTP stack (https://github.com/Metaswitch/sprout/blob/dev/sprout/handlers.cpp#L269).

Fairly annoying as it makes debugging registration timeouts harder.

**Comment by rkd-msw** [comment]
OK, I've got them logged to SAS with #1329, but the detailed timeline view isn't very good, so I'm going to add a high-level SAS log before closing this.

![2016-02-23_20h22_42](https://cloud.githubusercontent.com/assets/4363492/13263802/81c69eaa-da6b-11e5-8ae4-fd4da96b5c18.png)

**Comment by rkd-msw** [comment]
Now done.
