### ISSUE TITLE
Regstore NOTIFYs only sending deltas 

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/sprout#1219]
https://github.com/Metaswitch/sprout/blob/dev/sprout/regstore.cpp#L355

The NOTIFY constructed and sent by the regstore when updating bindings currently only sends information on the bindings that have expired, rather than the full current view held in the AoR. There also appears to be no means to send a message on a refresh. 
The proper behaviour according to the spec should be to send a full snapshot of the current view of bindings on each update.

The send_notify function will need to be modified to enable passing in the full map of current bindings, and to set the correct states for each member. There will also need to be some consideration of what point in the logic to send the notify, as to whether all bindings and subscriptions should be updated first, or whether each snapshot should be sent on the point of updating each single binding.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/1260
