### ISSUE TITLE
Rf billing incorrect for Term Interim and Stop ACRs when using Sentinel VoLTE TAS.

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#1222]
For a basic VoLTE call it appears that the Term Interim ACR is incomplete and the Term Stop ACR is not generated. This seems to be due to the S-CSCF using the Call-ID for the terminating leg it sends to the TAS for the Start ACR, and the Call-ID for the terminating leg sent by the TAS (to the S-CSCF) for the Interim and Stop ACRs. As a result, Ralf is unable to lookup the session for the latter two cases. All of this is probably due to the TAS acting as a B2BUA. A SAS trace and Wireshark capture of the Rf interface at the CDF will be uploaded to a diagnostics folder.

Also, I do not know if this is intentional or not, but Diameter ACR/ACA flows for Interim records are not displayed in SAS ladder diagrams.

**Comment by plfrancis** [comment]
Please ignore the last comment regarding Interim records not being displayed in SAS ladder diagrams. After reviewing a few more traces, the Orig Interim record is being displayed.

**Comment by AlexHockey** [comment]
@plfrancis this should be fixed in the linked PR. Please can you take it and retest?

**Comment by plfrancis** [comment]
The Term Stop ACR is now being generated correctly, but it looks like the Term Interim (ACK) ACR is being duplicated. Is this the intended behavior? I will upload a SAS trace.

**Comment by AlexHockey** [comment]
I'm fairly sure this is a TAS problem. The flow on the initial INVITE is (excluding the UEs):

```
P-CSCF(orig) -> sprout(orig) -> TAS(orig) -> sprout(orig/term) -> TAS(term) -> sprout(term) -> P-CSCF(term)
```

The TAS starts a new dialog at every hop, so we end up with three dialogs. Sprout does not record-route on the middle one, so the ACK flows like this. 

```
P-CSCF(orig) -> sprout(orig) -> TAS(orig) -> TAS(term) -> sprout(term) -> P-CSCF(term)
``` 

So the TAS should receive an ACK from sprout on dialog 1, then send one to itself on dialog 2, then send one to sprout on dialog 3. However it ends up sending two ACKs on dialog 3. The ACKs are separate transactions (they have different Via headers) but they are acknowledging the same response (they have the same Cseq). 

I'm going to close this issue. Please can you raise this with the TAS vendor.
