### ISSUE TITLE
ENT log not issued when sas_server not set

### ISSUE THREAD

**Issue by dcollins991** [Metaswitch/sprout#1226]
For test case, ENT-CL_SPROUT_INVALID_SAS_OPTION, the sas_server option is removed from the shared_config file, the file is uploaded, and sprout is restarted.  Sprout no longer issues the ENT log beginning with, "The sas_server option in /etc/clearwater/config is invalid or not configured...".  However a Warning is issued in the sprout log.  Paradoxically Homestead does issue the ENT log when the sas_server option is removed.  The issue was detected during V8 regression testing.  The issue can be reproduced by removing the sas_server line in shared_config, uploading the shared_config file, and then restarting Sprout.

**Comment by mirw** [comment]
Probably same fix as https://github.com/Metaswitch/ralf/issues/181.  Holding off doing anything more on this until we've resolved what we're doing there.

@JimBunch, I'm guessing this isn't critical - please update this issue if it is.

**Comment by JimBunch** [comment]
Not critical.
