### ISSUE TITLE
scribbler in stack.cpp init_stack()

### ISSUE THREAD

**Issue by dimbleby** [Metaswitch/sprout#1228]
[This code](https://github.com/Metaswitch/sprout/commit/99e4433afe75a4d70ae11445d58183fc253dabf8/sprout/stack.cpp#L633-634) calls `pj_strdup2` on an uninitialized pointer.  

That won't work - it'll just scribble into whatever the pointer happens to be pointing at.

**Comment by bossmc** [comment]
Marking as high-priority as this sounds like a recipe for runtime crashes/memory scribbles.

**Comment by bossmc** [comment]
@JimBunch - Does this feel critical to you?

**Comment by JimBunch** [comment]
Marking as critical because it is difficult to predict the impact of a scribbler. It could cause an outage or service affecting problem.

**Comment by mirw** [comment]
I think this needs to use `pj_strdup3` instead.

**Comment by mirw** [comment]
I've coded and am testing a fix.
