### ISSUE TITLE
ICSCF generates an ACR for Cx request on REGISTER

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/sprout#1245]
According to [TS 32.260 Table 5.2.1.1](http://www.3gpp.org/DynaReport/32260.htm), an EVENT ACR should be generated on:

> I-CSCF completing a Cx Query that was issued in response to a SIP INVITE

This is implemented in the `ICSCFRouter` code under [`get_scscf`](https://github.com/Metaswitch/sprout/blob/dev/sprout/icscfrouter.cpp#L94=L103) such that any call to that function causes an EVENT ACR to be sent, regardless of the SIP message being handled at that time.  This means that we'll send an EVENT ACR for the Cx lookup related to REGISTERs and for all  out-of-dialog requests that flow through the core.  This is most obvious with REGISTERs since these occur commonly and we generate double the expected number of billing events for each flow.

**Comment by JimBunch** [comment]
Marked as critical since it affects the accuracy of the billing.
