### ISSUE TITLE
Sprout generates log spam for REGISTERs with reused credentials.

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#1261]
When a UE performs a re-registration with reused credentials Sprout generates the following log spam at log level 2:

```
17-11-2015 15:44:33.428 UTC Warning authentication.cpp:242: Received an authentication request for 3196910000@vm1.richlab.datcon.co.uk with nonce 79424c77495f1dc6, but no matching AV found
```

Given this is typical behavior for many UEs, this log should probably be moved to a lower logging level (or modified to identify a more specific form of error). This log becomes particularly annoying during traffic runs which simulate re-registrations with reused credentials.

**Comment by mirw** [comment]
I agree that this should be removed.  It should be a trivial change.  It's probably worth doing a quick review of other error/warning logs.
