### ISSUE TITLE
SAS logging of AS chains is probably wrong

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/sprout#127]
There is code in sprout which changes the trail identifier on an incoming INVITE if it correlates the INVITE to an existing AS chain.  This is probably wrong as the INVITE has already been logged to SAS with the original trail identifier, and changing it runs the risk of the right markers not being raised on this original trail.

SAS already has the ability to correlate multiple trails on SIP call identifier, so it's not necessary for Sprout to do anything in this case.

**Comment by JimBunch** [comment]
This needs to be high priority so we can easily troubleshoot VoLTE calls that are utilizing the SAS.

**Comment by AlexHockey** [comment]
I'm not sure the ICID approach is sufficient. Normally the P-CSCF would add an ICID to the initial invite but bono doesn't. So we need to at least implement direct trail association. I thin we should add ICID association as well, as this will fix the issues I pointed out related to OOTB calls.

**Comment by mirw** [comment]
I agree that Bono doesn't add an ICID, but I think it should - TS 24.229 suggests so.  Can't we fix Bono and add ICID association?

**Comment by AlexHockey** [comment]
We could enhance Bono, but I don't think we should do that as a bug fix (as 24.229 requires the P-CSCF to do quite a lot with the P-Charging-Vector, such as storing it locally, re-adding it to in-dialog requests, stripping the value supplied by the UE, adding IOIs, etc). 

Additionally there may also be circumstances where a P-CSCF is misconfigured (say) and doesn't add an ICID. If the AS preserves the ODI token it would be a shame for sprout not to correlate across the AS.

Lastly TS 24.229 allows a B2BUA AS to preserve or change the ICID as it sees fit. It may also preserve/strip the ODI token as it sees fit. I think there *will* be scenarios where an AS preserves the ICID but strips the ODI token. I'm not sure if there will be scenarios where the AS preserves the ODI but changes the ICID, but again seems a shame for sprout not to correlate the two dialogs in this case.

So I still think we should do both.
