### ISSUE TITLE
Sprout crashes continuously if SAS is not running.

### ISSUE THREAD

**Issue by tcaterisano** [Metaswitch/sprout#1271]
We've noticed that in the released CC V8 software, Sprout will not start up if the SAS VM is not running. An assert is seen in this case coming from pjsip.  If Sprout is running, it simply reports that SAS is not contactable and continues to run with no asserts when a SAS VM is stopped. This issue only occurs when SAS and Sprout are down first and you try to start Sprout.  Homestead and Ralf do not seem to have this issue, only Sprout. Presumably this is because the issue lies within pjsip as indicated by the Assert seen in the Sprout log.

```
using API version 1
01-12-2015 17:17:47.667 UTC Status pluginloader.cpp:148: Finished loading plug-ins
01-12-2015 17:18:04.951 UTC Warning authentication.cpp:242: Received an authentication request for 9724910003@os1.richlab.datcon.co.uk with nonce 49a5f6cc5e55e658, but no matching AV found
01-12-2015 17:18:20.822 UTC Warning namespace_hop.cpp:74: Failed to retrieve cross-namespace socket - recvmsg returned 0 (0 Success)

01-12-2015 17:18:20.823 UTC Error sas.cpp:460: SAS connection to sas.os1.richlab.datcon.co.uk:6761 failed: 88 Socket operation on non-socket
01-12-2015 17:18:21.529 UTC Error pjsip: Assert failed: ../src/pj/activesock.c:200 sock!=0 && sock!=(-1)
01-12-2015 17:18:30.277 UTC Error pjsip: Assert failed: ../src/pj/activesock.c:200 sock!=0 && sock!=(-1)

Signal 6 caught

Basic stack dump:
```

**Comment by bossmc** [comment]
This is https://github.com/Metaswitch/cpp-common/issues/408, the fact that PjSIP thinks 0 is an invalid socket is a bug, but 0 should always be stdin so this should be unhittable.

**Comment by rkd-msw** [comment]
https://github.com/Metaswitch/cpp-common/issues/407 should have fixed this - can you retest?

**Comment by tcaterisano** [comment]
Sprout no longer crashes when sas is down. I see this in the log now and sprout started fine.

10-12-2015 22:34:00.782 UTC Warning namespace_hop.cpp:75: Failed to retrieve cross-namespace socket - recvmsg returned 0 (0 Success)
