### ISSUE TITLE
calling an unregistered number results in 600 (Busy everywhere)

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1273]
The quaff test call "Basic Call - Unregistered number" fails when it receives a 600 on a INVITE to an unregistered number.

Diags are available.

**Comment by rkd-msw** [comment]
I've looked at the SAS trace provided. What's happening is that:

* The HSS is returning a Location-Information-Answer with no capabilities and no S-CSCF URI. This is valid and should trigger the I-CSCF to pick an S-CSCF from its configured list.
* However, the I-CSCF has no configured S-CSCFs to choose from. There's a SAS log to help diagnose this - "There are no configured S-CSCFs - request cannot be processed"
* The right behaviour in this case is to reject with a 600 (per TS 24.229: "If the I-CSCF cannot select a S-CSCF which fulfils the mandatory capabilities indicated by the HSS, the I-CSCF shall send back a 600 (Busy Everywhere) response to the user.")

If you set up the /etc/clearwater/s-cscf.json file (per "Setting up S-CSCF configuration" at http://clearwater.readthedocs.org/en/latest/Manual_Install/index.html#provide-shared-configuration), you should start seeing 480 errors again.

(It's worth noting that I have https://github.com/Metaswitch/sprout/pull/1188 in the works, which should make the default s-cscf.json config more sensible and help avoid this sort of error.)

**Comment by dtheobald** [comment]
Understood
