### ISSUE TITLE
The BGCF fails to route tel URIs that don't include a routing number.

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1316]
If the URI classifier determines that the request URI to be forwarded to the BGCF is not a SIP URI and there is no routing number contained within the URI, the BGCF will not attempt to find a route for the number.
This means that if we have a wildcard routing record to catch any tel URIs that need to be routed, for example:
{
  "name" : "Wildcard number matching"
  "number" : "*"
  "route" : ["sip:10.225.84.205:5058"]
}
and the BGCF receives a tel URI with no routing number, the above record will not be matched and no routing target selected. This results in Sprout reporting a '404'- no route to target error.

The code for selecting a BGCF route based off the domain or number contained within the request URI is found in bgcfsproutlet:
https://github.com/Metaswitch/sprout/blob/dev/src/bgcfsproutlet.cpp#L159
This needs to be modified to assign bgcf_routes in cases where we have a tel URI with no routing number.

**Comment by JimBunch** [comment]
Marked as critical because it is service affecting in that calls may not be routed correctly.
