### ISSUE TITLE
Sprout might never restart (race condition)

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/sprout#1326]
There appears to be the possibility of a rare race condition in Sprout. 

Due to the logic of [the Sprout monit script](https://github.com/Metaswitch/sprout/blob/51024458ddc5391f5c29c7be2eb882f33c5ab218/sprout-base.root/usr/share/clearwater/infrastructure/scripts/sprout.monit), if sprout is quiesced/stopped, and another process starts with the same PID as it had just after this, before monit has had time to check, we do not revive.

The first check in this script just checks that the PID file exists, and that the PID is a running process, not that that process is sprout. 
As such, in the condition that another process has taken the PID, we do not attempt to start sprout.

Further to this, when the poll scripts fail, the abort commands run fail silently if they cannot find the right PID from within the subset of processes named Sprout. As Sprout is not running, it will never find the PID. Because of this, the PID file is also never cleaned up.

This will be a possible issue in all of our monit files

**Comment by mirw** [comment]
I wonder if the simplest fix here is to make the abort script delete the PID file if it isn't sprout?

What do you think, @johadalin?

**Comment by johadalin** [comment]
Seems like a reasonable suggestion. 
Is the same potential race present in all of our processes where we monitor the PID file? 
Would be good if we can get monit to check that the PID matches for a process with a name matching the monit group or something like that, so that all the other monitored processes drop out for free

**Comment by mirw** [comment]
Discussed with @johadalin and agreed that there's no need to get monit to check PIDs - my proposed fix above should be sufficient (and simpler/more robust).

Unclaiming this issue, as I'm not going to be able to work on it imminently.

**Comment by johadalin** [comment]
@rkd-msw I believe all the linked changes above should resolve this issue, and the linked homer issue https://github.com/Metaswitch/crest/issues/305. I'm going to pass this one back to you, as i think you should keep your eyes open just in case this leads to Monit behaving strangely on our VM images. 
I don't think there is much risk of things going wrong, and i don't think there's much you could really test, so this is mostly just for awareness.

It may be worth just testing a couple of nodes/processes work with this fix as we expected. A simple replication could be set up on the old code by the following:

* Change the value in /var/run/<proc>/<proc>.pid to match a different, running process.
* Stop the <proc> process.
* Wait for monit to detect failure through our health-checking polls.

At this point, the old code would never restart the process. With the new changes, the bad pidfile should be cleaned out, monit should detect the process is dead, and restart it.
Note: Any processes that do not have a poll script/health check will not resolve themselves. This is not a regression, and i believe all of our service critical processes do have polls for liveness. Shout if you disagree, or close this down if you don't.

**Comment by rkd-msw** [comment]
That test didn't work. On 10.0.0-170127-~255.00.0-170127.020342, I don't see your change in /etc/init.d/sprout, and your commits don't seem to be in CC_10_dev - some kind of merge issue?

**Comment by johadalin** [comment]
Resolved the CI issues, so these changes should now have been merged across and be present in your test images. Passing back to you as before, let us know if the changes still haven't made it across, as that would indicate a deeper problem with our infrastructure.

**Comment by rkd-msw** [comment]
Yep, fixed on `10.0.0-170131-~255.00.0-170131.020417`.

We discussed the 'all of our service critical processes do have polls for liveness' thing - the only one I've spotted that doesn't was NTP, but you didn't think this was a big issue, and given that we haven't seen any issues in practice, I'm inclined to agree.
