### ISSUE TITLE
Sprout can't load any plugins on XFS

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#1340]
As debugged by Jia Xuan in http://lists.projectclearwater.org/pipermail/clearwater_lists.projectclearwater.org/2016-March/002723.html, Sprout loads plugins only if their directory entry's `d_type == DT_REG` (https://github.com/Metaswitch/sprout/blob/dev/src/pluginloader.cpp#L73).  However, according to the [readdir(3) man page](http://linux.die.net/man/3/readdir), not all file systems support `d_type` - in particular, XFS doesn't.

Failing to load plugins means that Sprout can't load any of its business logic, and so doesn't do anything.

**Comment by rkd-msw** [comment]
I'm going to fix that line of code to cope with DT_UNKNOWN, and see what happens if you have a directory or a symlink inside the plugins dir. (I expect dlopen will return NULL and we'll just skip it.)

**Comment by bossmc** [comment]
I'd not be suprised if `dlopen` followed symlinks but it should fail sensibly on directories/blockdevices/etc.
