### ISSUE TITLE
Sprout does not apply default handling to ASs if it has received a 100 trying.

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#1346]
TS 24.229 states that an S-CSCF should apply default handling if it:

> a)	fails to receive a SIP response within a configurable time; or
> b)	receives a 408 (Request Timeout) response or a 5xx response from the AS without previously     receiving a 1xx response to the original SIP request, and without previously receiving a SIP request     from the AS that contained the same original dialog identifier as the original request;

Sprout does not implement the bit that says "without previously receiving a 1xx response to the original SIP request, and without previously receiving a SIP request from the AS that contained the same original dialog identifier as the original request;". 

This means that if a UE sends a 5xx response that gets passed back to sprout via an AS, sprout will apply default handling when it shouldn't.

**Comment by mirw** [comment]
Flagging as critical because this is call-service affecting.  @JimBunch, please shout if you disagree!

**Comment by JimBunch** [comment]
I agree.

**Comment by AlexHockey** [comment]
I have an update on this issue. On closer inspection of the code it looks like sprout treats an AS as responsive (so won't apply default handling) if:

* It gets a request from the AS with the same ODI token it put on the request to the AS (this is correct). 
* It gets a 100 trying back from the AS (this is wrong as IMS does not treat 100 trying as a 1xx response - yes, really). 

If an AS sent a 100 response followed by a 5xx, the specs say the AS should have default handling applied to it, but sprout would not do so. This means that actually sprout applies default handling less frequently than it should.

**Comment by AlexHockey** [comment]
This is potentially quite a big bug fix (~10 hours) as it will involve re-doing the AS alarm S-CSCF UTs which will break when the fix is implemented.
