### ISSUE TITLE
Possible deadlock - worker thread and quiescing thread can take connection manager lock and transport lock in different orders

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1351]
Split out from https://github.com/Metaswitch/sprout/issues/1325 to keep issues separate.

**Comment by rkd-msw** [comment]
The issue here is that:

* PJSIP can hold the transport lock, then call `ConnectionTracker::connection_active` which takes the connection manager lock
* `ConnectionTracker::quiesce` can take the connection manager lock, then call `pjsip_transport_shutdown`, which takes the transport lock

Two threads taking locks in different orders is a Bad Thing.

We initially thought all of this happened on the PJSIP transport thread and that we could resolve it by just removing the lock and checking that we were on the transport thread. Alas, `ConnectionTracker::quiesce` is called from the quiesce_unquiesce_thread (https://github.com/Metaswitch/sprout/blob/dev/src/main.cpp#L1258).

Our current best thinking is to merge the quiesce_unquiesce_thread and the PJSIP transport thread together - so that in [this loop](https://github.com/Metaswitch/sprout/blob/af2a44862bdaf33ecc0f982c8d483ab2323b8abc/src/stack.cpp#L163), rather than just calling `pjsip_endpt_handle_events` continuously, we'll call `pjsip_endpt_handle_events` then check if we need to do anything quiescing-related.

This isn't an obviously foolproof plan - there might be some dragons (like us never making progress in our quiescing because we're not calling `pjsip_endpt_handle_events`) - but I can't see anything obviously wrong with it and it's worth a try.

**Comment by mirw** [comment]
@johadalin, what's the status of this?  It looks like #1377 is almost ready to go.  Can we get this critical issue closed down (or de-criticalized if #1378 is to be believed).

**Comment by johadalin** [comment]
I just have the last changes to add, and it can be merged. 
I'm changing the critical tag to high priority, as Jim does not want this in CCv9.
