### ISSUE TITLE
upload_shared_config does not trigger nodes to add themselves

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/sprout#1375]
#### Symptoms

Spun up a standard deployment through Chef for testing, and when investigating logs, noticed that the sprout logs were repeatedly showing " Warning namespace_hop.cpp:75: Failed to retrieve cross-namespace socket - recvmsg returned 0 (0 Success)". Suggesting that clearwater-infrastructure had not restarted correctly after the application of shared config.

Looking at the queue manager logs, no entries were seen in the restart queue for sprout (the node on which shared_config is initially uploaded). Testing on other nodes, modifying and re-uploading shared config does not appear to trigger the node to add itself to the restart queue.

#### Impact

Particularly in split-network deployments, this will prevent changes dependent on clearwater-infrastructure restarting from being picked up correctly.

**Comment by johadalin** [comment]
Marking as critical due to potential for impact, and assigning to Ellie, as she agreed to take it on.

**Comment by graemerobertson** [comment]
I think @rkd-msw saw this earlier too
