### ISSUE TITLE
SPROUT_SESS_CONTINUED_AS_COMM_ERROR alarm not clearing

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1384]
#### Symptoms

After causing the alarm I could not get it to clear. 

#### Release and environment 

release-94

#### Steps to reproduce
1. Set up simple system with appropriate iFC and one sprout node and ensure no alarms or traffic.
2. Bring up AS
3. Make call involving AS
4. Stop AS
5. Make call involving AS and note that sprout issues alarm
6. Bring up AS
7. Make call(s) involving AS, but alarm doesn't clear even after several successful calls and lengthy wait.

Diags have been collected.

**Comment by JimBunch** [comment]
This problem is marked as critical because it is an issue with the new AS alarms feature.

**Comment by dtheobald** [comment]
BTW - I see the same behavior with the session terminated alarm.

**Comment by AlexHockey** [comment]
Thanks @dtheobald for the write up of the steps to reproduce. In step 7, it sounds like you made some successful calls then waited for a long time with no traffic going through the system. Is that correct? If so, I wouldn't expect that to clear the alarm. However I think if you continued to make successful calls the alarm would clear after up to 10 minutes.

The reason for this is down to how sprout tracks AS failures, which is based on 5 minute intervals. 

* When an AS is invoked if it's a failure sprout records this and raises the alarm if it is currently cleared.
* Then, regardless of whether the AS succeeded or failed, it checks whether we have moved into the 
next time interval. If we have, sprout checks the *previous* interval. If there were no failures in that interval it clears the alarm. 

This means if you make call your successful calls too close to a failure, the successes will be in the same time period as the failure. 

Could you retry, but try making a successful call every couple of minutes and see if the alarm clears after 10 mins?

**Comment by dtheobald** [comment]
I figured it must be something like that, so thanks for the explanation.

I retried using that scenario and the alarm cleared.
