### ISSUE TITLE
Sprout is performing a UDP DNS lookup that fails

### ISSUE THREAD

**Issue by tcaterisano** [Metaswitch/sprout#1386]
Sprout is performing a UDP DNS lookup that fails
#### Symptoms

04-04-2016 15:35:55.359 UTC Error dnscachedresolver.cpp:567: Failed to retrieve record for vm7.richlab.datcon.co.uk: DNS server returned answer with no data
04-04-2016 15:35:55.359 UTC Error dnscachedresolver.cpp:567: Failed to retrieve record for _sip._udp.vm7.richlab.datcon.co.uk: Domain name not found

#### Impact
Sprout overloads at low call rates

#### Release and environment 
sprout                         9.0.0-1-1.0.0-160329.193924

#### Steps to reproduce
traffic at 10 cps

**Comment by mirw** [comment]
@tcaterisano, a couple of comments on this.

*   You set the impact to say sprout "overloads".  What do you mean by this?  Does Sprout start throttling?  I would expect Sprout just to fail the call.
*   The obvious explanation for this is that the DNS server is replying with an empty response?  Are you sure that this is not happening?  For example, do you have SAS trace or DNS network capture showing a successful DNS response that then goes on to hit this issue?

**Comment by tcaterisano** [comment]
tcpdump does not contain any references to the dns lookup yet sprout reports this in the sprout log file.

04-04-2016 16:46:11.053 UTC Error dnscachedresolver.cpp:567: Failed to retrieve record for scscf.s prout.vm7.richlab.datcon.co.uk: DNS server returned answer with no data
04-04-2016 16:46:12.090 UTC Error dnscachedresolver.cpp:567: Failed to retrieve record for _sip._u dp.scscf.sprout.vm7.richlab.datcon.co.uk: Domain name not found

**Comment by mirw** [comment]
@tcaterisano, as just discussed, it sounds like this isn't the cause of your overload - this is just that you don't have a NAPTR record, and so we query SRV for both TCP and UDP (and UDP has no results).  I'd suggest this is WAD.

**Comment by tcaterisano** [comment]
Corrected this log message by adding a NAPTR record.  Checking the docs to be sure we instruct this as the proper config.

vm7.richlab.datcon.co.uk.  NAPTR 10  10  "S"  "SIP+D2T"  ""  _sip._tcp.scscf.sprout.vm7.richlab.datcon.co.uk.
