### ISSUE TITLE
nonce count of zero is not rejected with a 400 (bad request)

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1390]
#### Symptoms

Responding to a fresh auth challenge with a nonce count of zero is accepted (i.e., SIP 200 OK) instead of being rejected with a SIP 400 Bad Request.

#### Release and environment 

release-94

#### Steps to reproduce
1) Attempt fresh registration
2) Respond to auth challenge with nc=00000000

Diags are available.

**Comment by JimBunch** [comment]
Marked as critical since it is a capability of a new feature.

**Comment by mirw** [comment]
I think this is for back-compatibility with the previous release.  For the first response to a challenge, we allow the nonce count to be any value.  Subsequently, the nonce count must strictly increase.

I don't have a major objection to excluding 0, but I believe it would have been allowed by the previous release, so we may break behavior on upgrade.

@AlexHockey, do you agree?  If so, I think we should check with @JimBunch before changing the behavior here.

Incidentally, it's worth testing that subsequent challenges do not permit a decreasing nonce_count.

**Comment by dtheobald** [comment]
I was testing this statement from the func spec - ```On a fresh challenge the expected nonce count is 1, but REGISTERs with nonce counts less than 1 are rejected with a SIP 400 Bad Request.```

**Comment by mirw** [comment]
Agreed, and maybe we should correct that.  Do you agree, though, that previous versions of the software would have permitted 0?

**Comment by dtheobald** [comment]
I'd suspect that you are correct, but I'd have to try it to know for sure. Do you want me to verify?

**Comment by AlexHockey** [comment]
I have taken a look at the PJSIP code and I'm about 90% sure that we would have permitted nc=0 before the recent change. However if it's easy to check the old behavior I think we should, as it is more in keeping with RFC 2617 to forbid nc=0.

**Comment by AlexHockey** [comment]
@dtheobald how hard would this be to test on the old code?

**Comment by dtheobald** [comment]
I can spin up an old version relatively easily. What version should I go back to? Is release-93 good enough?

**Comment by AlexHockey** [comment]
Yeah, release-93 is fine.

**Comment by dtheobald** [comment]
Older releases accept a zero nonce count on a fresh registration.

**Comment by mirw** [comment]
@dtheobald, thanks for testing!

@JimBunch, you marked this as critical.  I'd like to argue it's WAD, for backwards-compatibility reasons.  Please let me know if you agree, and we'll clarify the specification.

**Comment by JimBunch** [comment]
OK, I will remove the critical marker. Please update the FSpec and we will fix the test cases to allow a nonce count of zero.

**Comment by mirw** [comment]
@AlexHockey, are you OK to fix up the FS?  (Should be pretty quick.)

**Comment by AlexHockey** [comment]
Done. Passing back to Doug to adjust the testcases.

**Comment by dtheobald** [comment]
I've adjusted the test cases.
