### ISSUE TITLE
Sprout rejects calls with 503, reports that it is due to overload control in SAS

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/sprout#1399]
#### Symptoms

The system is CCv9 latest build, on openstack, though this has also been seen on VMware.

Running load at ~20 calls per second, occasional calls are rejected with a SIP 503 Service unavailable. The SAS trace for such a call states that this: "SIP request rejected due to overload control"

In the Sprout logs at this time we see the log text:
`13-04-2016 21:13:43.787 UTC Warning scscfsproutlet.cpp:1769: No charging role in Route header, assume originating
13-04-2016 21:13:43.788 UTC Error dnscachedresolver.cpp:567: Failed to retrieve record for os2.richlab.datcon.co.uk: DNS server returned answer with no data
13-04-2016 21:13:43.788 UTC Error dnscachedresolver.cpp:567: Failed to retrieve record for _sip._udp.os2.richlab.datcon.co.uk: Domain name not found`

Unfortunately we did not have a pcap running between sprout and the DNS at this point.

#### Impact

This issue causes the call attempt to fail, and so will initially be marked as critical.
It is however very intermittent, and the cause is unclear at the moment, so we may eventually wish to downgrade it if we can't reliably reproduce it to gather the correct diagnostics, or if the number of calls dropped is not significant enough.

#### Diagnostics
Attaching the logs from Sprouts 1 and 2, and putting them with the SAS trace in the diags space. This is from the latest SAS so will need to be viewed on an equivalent version (9.2.10). The Richardson OS2 (openstack 2) deployment has a SAS of this version if needed. 
More diags should be gained when we see this again.

[sp-1-access_20160413T210000Z.txt](https://github.com/Metaswitch/sprout/files/218090/sp-1-access_20160413T210000Z.txt)
[sp-1-sprout_20160413T210000Z.txt](https://github.com/Metaswitch/sprout/files/218089/sp-1-sprout_20160413T210000Z.txt)
[sp-2-access_20160413T210000Z.txt](https://github.com/Metaswitch/sprout/files/218092/sp-2-access_20160413T210000Z.txt)
[sp-2-sprout_20160413T210000Z.txt](https://github.com/Metaswitch/sprout/files/218091/sp-2-sprout_20160413T210000Z.txt)

**Comment by rkd-msw** [comment]
Your DNS logs are a symptom, not a cause:

* Sprout sends a 503 Service Unavailable at 21:13:43.783
* Sprout gets an ACK for that - but we sent the 503 response statelessly so we've forgotten about the transaction
* so we strip the Route header (`Route: <sip:scscf.sprout.os2.richlab.datcon.co.uk;transport=TCP;lr;orig>`) and attempt to forward it based on the Req-URI (`sip:3176914736@os2.richlab.datcon.co.uk`)
* standard SIP routing rules mean we have to do a NAPTR lookup for os2.richlab.datcon.co.uk and so on - this is the only time we'll ever try and resolve os2.richlab.datcon.co.uk (rather than doing internal Sproutlet routing or trying to resolve scscf.sprout.os2.richlab.datcon.co.uk)
* we look up _sip._tcp.os2.richlab.datcon.co.uk when NAPTR and SRV/UDP fail, find sprout-1 and send the ACK there (this is at 21:13:43.790 in the detailed timeline)
* the ACK probably just gets silently dropped there

**Comment by rkd-msw** [comment]
Looking through the logs, some thoughts:

There's a 75%-25% split in how load is balanced between the Sprouts, which suddenly changes at about the time of the SAS trace:
  * at 21:13:43.748 and before, sprout-1 is handling ~50 SIP requests a second, but at 21:13:45.763 and afterwards it's handling ~150
  * at 21:13:43.786 and before, sprout-2 is handling ~150 SIP requests a second, but at 21:13:45.787 and afterwards it's handling ~50

You can see this by looking for lines like "Maximum incoming request rate/second unchanged - only handled 273 requests in last 2012ms, minimum threshold for a change is 286.345123" (that's requests per 2 seconds, so divide by 2)


There are some 503 and 504 responses from Homestead at 21:13:20 and 21:14:36:

```
13-04-2016 21:13:20.936 UTC Error httpconnection.cpp:762: cURL failure with cURL error code 0 (see man 3 libcurl-errors) and HTTP error code 503
13-04-2016 21:13:20.936 UTC Error hssconnection.cpp:615: Could not get subscriber data from HSS

13-04-2016 21:14:36.075 UTC Error httpconnection.cpp:762: cURL failure with cURL error code 0 (see man 3 libcurl-errors) and HTTP error code 504
```

sprout-1 sees errors at both times, sprout-2 only at 21:13:20.

There are connection failures scattered throughout, which can't be very healthy:

```
13-04-2016 21:12:41.959 UTC Error pjsip: tcpc0x7fd52867 TCP connect() error: Operation timed out (PJ_ETIMEDOUT) [code=70009]
13-04-2016 21:12:41.959 UTC Warning pjsip: tsx0x7fd50c6d4 Failed to send Request msg INVITE/cseq=1 (tdta0x7fd50c71ec50)! err=70009 (Operation timed out (PJ_ETIMEDOUT))
```

Sadly these diagnostics aren't very good - it would be nice to know the target IP/port.

**Comment by rkd-msw** [comment]
Maybe the change in load distribution is because sprout-2 sends a 503 and Perimeta moves traffic away from it.

**Comment by rkd-msw** [comment]
Are the NTP clocks in sync here? There's about a 20ms gap between the times Perimeta reports for each message and the times Sprout reports for each message, and 14ms between the two Sprouts. If that's actual network latency, that's greater than the 10ms we recommend within a site.

**Comment by rkd-msw** [comment]
With a rate limit of 300 requests/second, which we have on Sprout-1, we'd need 51 requests in a 100ms period to get a 503 (30 to use up our 30 requests/0.1 second refill rate, 20 to use up the max tokens in the token buckets, 1 to be rejected).

On sprout-2, between 21:13:41.769 and 21:13:43.786  (i.e. over 2 seconds) we handled >320 requests - we know this because we changed the permitted request rate at 21:13:43.786 and the threshold to increase it was 320.420776. Could we have handled significantly more than 320, and could 51 of those have been in a 100ms window? It doesn't feel impossible. Should we add some more diagnostics so we can tell?

**Comment by rkd-msw** [comment]
Back to you to comment on:

* whether NTP clocks are in sync or whether there are 20ms network delays
* if you know of any reason why load would be unevenly distributed between the two Sprouts
* if you know of any reason why load would be bursty (>51 requests in a 100ms period)

**Comment by johadalin** [comment]
Everything appears to be in sync, and there appears to be next to no delay in pings between nodes (less than 1ms).
The load should be smooth, and we can't see any reason why it would be split unevenly between the nodes. This set of diags were gathered in a deployment with a v3.7.(40 i think) perimeta if that makes a difference.
Are there any diagnostics that could isolate whether it is any of those points causing the issue?

We have currently backed that deployment down to CCv8 and are re-running tests. I'll update if we see anything like this there.

**Comment by rkd-msw** [comment]
My strong suspicion is that you're hitting the same issue as https://github.com/Metaswitch/homestead/issues/330 - short (~20ms) periods where Clearwater receives wildly disproportionate amounts of load. `max_tokens=100` might help here too.

**Comment by mirw** [comment]
I agree that these look the same.  I wonder what's causing the bursty-ness?  One possibility is DNS lookups - we share our cache between threads, so while a DNS request is outstanding we'll hold up all other SIP or HTTP requests for the same destination.  Maybe we should tweak DNS resolution to use the old (out-of-date?) value until the DNS query succeeds (asynchronously?)

**Comment by tcaterisano** [comment]
max_tokens=100 does help. It seems to have eliminated the 503 overload errors.

**Comment by tcaterisano** [comment]
Can we make max_tokens=100 the default and close this issue?

**Comment by rkd-msw** [comment]
I'll sort out a change making max_tokens default to 100, but as with https://github.com/Metaswitch/homestead/issues/330, we still need to understand where the burstiness is coming from. If there's a Clearwater issue that makes traffic come in bursts, then there's a risk of further issues where we send bursts of traffic to other devices (e.g. third-party HSSes) which can't cope with the overload.

**Comment by johadalin** [comment]
max_tokens now defaults to 100, as per https://github.com/Metaswitch/sprout/pull/1403, so i am closing this issue down. 
The issue above will keep track of finding the source of the bursts in traffic, and fixing them if they are caused by Clearwater.
