### ISSUE TITLE
Clearwater may cause bursts in load, triggering overload

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/sprout#1401]
#### Symptoms

As seen in #1399 and https://github.com/Metaswitch/homestead/issues/330, overload protection and thresholding caused 503 responeses due to overload, even at low traffic rates. 
Some analysis of the homestead logs showed that this was being caused by the load becoming 'bursty'. It is currently unclear where the bursty-ness was introduced. 
The system these symptoms were seen on was running CCv9, and Perimeta 3.8.40, with no TAS in the call flow. The load was being driven by Abacus. 

The proposed change of setting "max_tokens=100" in shared conflict resolved the issue for testing purposes, and this may be the correct value for production systems going forward (rather than the current default of 20). However, we need to determine whether the bursty-ness was introduced by Clearwater, or whether it was some other factor (Perimeta, Abacus, networking issues etc).
#### Impact

If this is caused by Clearwater, it introduces instability into the call flow that could lead to call attempts being rejected by overload control when the system is not overloaded. 
If this is not caused by Clearwater, it may indicate that our threshold tolerances are too tight, and that this needs further investigation.
#### Release and environment

CCv9 and Perimeta 3.8.40 on VMware. Load driven by Abacus.
#### Steps to reproduce

With max_tokens set to the default of 20, running load at 20-30 cps caused the issue to appear with the setup as described above.
#### Further Information

It was suggested in #1399 that the bursty-ness could be introduced by DNS lookups. https://github.com/Metaswitch/cpp-common/pull/501 may resolve this if it turns out that this was causing the issue.

Analysis of whether the bursts in load follow DNS lookups, and/or of where in the call flow the bursty-ness was introduced is needed to determine the cause of the issue, and therefore to determine the necessary fix.

**Comment by johadalin** [comment]
@tcaterisano I am going to assign this issue to you, as I think the next step is for us to gather the correct diagnostics, which will need a running test system. If you think this can't be done during the run-up to release, let us know.
@rkd-msw As the pull request to fix what we think might be the potential cause of this is yours, can you advise on what diagnostics would be most helpful in the first instance?

**Comment by rkd-msw** [comment]
Access logs from Homestead again (to check when burstiness occurs), and PCAP trace from the DNS server (so we can check if DNS requests correlate with that burstiness).

If we can get PCAP trace elsewhere in the network (e.g. into Sprout), I wouldn't say no, but I realise that's higher-traffic and more difficult.

**Comment by sathiyan-sivathas** [comment]
We need a running test system for collecting diagnostics, so I'm going to mark this as blocked until we have that.

**Comment by johadalin** [comment]
@rkd-msw . Assigning this to you as we have now got a proper test team and test systems. 
I don't think we've seen overload from bursty traffic, but checking e.g. homestead logs again could be a good idea. Hopefully we can just close this down.

**Comment by rkd-msw** [comment]
I've taken a look at the data from a stress run which ran from 12:49:23 to 13:19:31 at ~29 CPS (where a "call" counts the leg from the caller and the leg to the callee - it's ~58 CPS if you count them separately) and ~89 RPS.

```
clearwater@stress-homestead-1:/var/log/homestead$ cat access_20170122T130000Z.txt | grep -v ping | cut -f2 -d " " | sed "s/..$//" | uniq -c | sort -nr | head
    120 13:16:05.8
     50 13:16:05.9
     44 13:16:06.0
     38 13:16:08.6
     38 13:16:06.2
     37 13:16:23.4
     37 13:16:22.9
     35 13:16:33.5
     35 13:16:27.3
     35 13:16:09.9
clearwater@stress-homestead-1:/var/log/homestead$ cat access_20170122T120000Z.txt | grep -v ping | cut -f2 -d " " | sed "s/..$//" | uniq -c | sort -nr | head
     34 12:56:28.6
     32 12:56:18.1
     31 12:50:02.7
     28 12:59:48.4
     27 12:47:40.7
     26 12:50:02.9
     26 12:46:54.2
     25 12:59:29.9
     25 12:50:50.8
     25 12:50:43.8
```

So the only 100ms window which saw a higher load than usual was 13:16:05.800-13:16:05.899, and that came just after a bust of Cassandra timeouts:

```
22-01-2017 13:16:05.448 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.452 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.472 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.532 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.544 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.628 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.672 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.684 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.720 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.768 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.776 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.792 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
22-01-2017 13:16:05.800 UTC Error cassandra_store.cpp:432: Cassandra request failed: rc=3, Exception: THRIFT_EAGAIN (timed out) [2]
```

So I think that's explainable by retries and requests that were blocked on Cassandra rather than any upstream burstiness.

That means I'm not seeing any of this burstiness - presumably it was an issue in the lab in Richardson which I haven't replicated - so I think it's safe to close this.

**Comment by rkd-msw** [comment]
Cassandra timeouts are covered by https://github.com/Metaswitch/homestead/issues/387.
