### ISSUE TITLE
RTRs don't always result in a challenge on reregistrations

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1406]
#### Symptoms

After sending an RTR for a reregistering user the user was challenged and subsequently re-authorized and starts reregistering. However, if another RTR is sent, the user is not challenged.

#### Impact

Unauthorized usage

#### Release and environment 

release-94

#### Steps to reproduce
1) Register a user and begin reregistering
2) Send RTR
3) User is challenged and registers again and starts reregistering
4) Send RTR
User is not challenged.

Diags have been collected.

**Comment by graemerobertson** [comment]
From the Homestead logs, only one Registration-Termination-Request is received by Homestead - on homestead-1 at 17:27:29.323. This matches the first SAS trace (it occurs between the unchallenged REGISTER and the challenged REGISTER).

Presumably you tried to trigger another RTR at some point soon after, but it never reached Homestead.

@dtheobald can you repro this reliably? If so, I think it would be worth getting packet capture from the HSS at the point when the RTRs are triggered (to see if the HSS is even attempting to send the RTR), and also checking that the HSS thinks the subscriber is registered at the point when the RTRs are triggered.

**Comment by dtheobald** [comment]
Yes, I can reliably reproduce this. I'll do that and wireshark the HSS.

**Comment by dtheobald** [comment]
I've reproduced (new diags captured) and you are correct the HSS is not sending the second RTR even though the user's state reverts to NOT-REGISTERED; which is what was fooling me. I'll see if I can figure out why it's not sending the second RTR.

BTW - I'm using the OpenIMS HSS.

**Comment by graemerobertson** [comment]
Has the user successfully re-registered, i.e. is the user's state set to REGISTERED before triggering the second RTR? It sounds like it is, and the SAS flows look fine. Have you seen this working in previous releases?

It sounds like an OpenIMS HSS problem. @rkd-msw do you have any input?

**Comment by dtheobald** [comment]
I've tried it again and what I noticed this time is that after the first RTR the user becomes NOT-REGISTERED and then REGISTERED again as expected, but then a short time later it becomes NOT-REGISTERED without attempting another RTR and stays that way after many (10+) successful re-registrations.

I've collected diags for this scenrio (example.3 directory)

**Comment by graemerobertson** [comment]
After the RTR, the subscriber tries to re-register (as normal) and gets a challenge which it never responds to. Instead, in the second SAS trace, it again tries to register (without an Authentication header) and receives another challenge. This flow works fine, and the HSS thinks the subscriber is REGISTERED.

However, the S-CSCF times out the first challenge after 30 seconds and triggers an SAR to the HSS with AUTHENTICATION_TIMEOUT set  (see the first SAS trace). Presumably this is triggering the state change in the HSS. We don't think it should do.

Is it possible to test with the subscriber responding to the first challenge?

I suspect this matches the behaviour from previous releases - have we definitely seen this working before?

**Comment by dtheobald** [comment]
@graemerobertson has verified that Clearwater is doing the right thing and that the problem lies in the OpenIMS HSS, so I'm closing this issue.

**Comment by graemerobertson** [comment]
Closing (on the assumption that Doug already meant to do that :eyes:)
