### ISSUE TITLE
SPROUT_REMOTE_VBUCKET_ERROR doesn't clear

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1422]
#### Symptoms

After cutting communications between GR sites and causing the ```SPROUT_REMOTE_VBUCKET_ERROR``` alarm, I restored communications and ran traffic, but the alarm doesn't clear.

#### Impact

Confusion

#### Release and environment 

release-94

#### Steps to reproduce
1) Bring up GR sites
2) Cut communications between sites
3) Cause ```SPROUT_REMOTE_VBUCKET_ERROR``` alarms
4) Restore communications
5) Run traffic, but alarm never clears

Diags have been collected.

**Comment by JimBunch** [comment]
Marking as critical since the alarm never clears and probably will require manual intervention to clear it.

**Comment by mirw** [comment]
Similar to https://github.com/Metaswitch/clearwater-etcd/issues/289?

**Comment by mirw** [comment]
@graemerobertson, please can you take a look?

**Comment by graemerobertson** [comment]
I've reproduced, and it's not immediately obvious to me why the alarm isn't being cleared :turtle: I'm going to add some more diags and repro again

**Comment by graemerobertson** [comment]
Ah, https://github.com/Metaswitch/cpp-common/blob/master/src/memcachedstore.cpp#L493 is just wrong :(

**Comment by graemerobertson** [comment]
I literally don't think we've _ever_ cleared a vbucket alarm, so that's good!

**Comment by graemerobertson** [comment]
@dtheobald are you happy to close this issue, or do you want to retest yourself first?

**Comment by dtheobald** [comment]
I'll close and then retest in the next cycle.
