### ISSUE TITLE
sprout rejects (with a 480) a de-registration with auth

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1423]
#### Symptoms

After merge of this commit https://github.com/Metaswitch/sprout/commit/4c3f4ece1ca6164147570038ec2b5329e40b4bcb, registrations with auth are rejected with a 480. I've backed out that commit and the de-registration sequence works as before.

#### Impact

Regression test failures.

#### Steps to reproduce
De-register (expires=0):and sprout responds with a challenge:
![pic1](https://cloud.githubusercontent.com/assets/6430927/14941763/7430fbc8-0f6d-11e6-96ad-056498452f72.png)

UE responds to challenge: 
![pic2](https://cloud.githubusercontent.com/assets/6430927/14941762/742b97be-0f6d-11e6-8cb8-a189515bb198.png)

The above SAS traces can also be found in the diags area.

**Comment by JimBunch** [comment]
Marking as critical since it is call processing service affecting.

**Comment by mirw** [comment]
SAS shows that the HSS is rejecting our UAR with a 5003 (IDENTITY_NOT_REGISTERED) - I think that's what causes the 480 response.

My suspicion is that this is because we send a MAR when we do the authentication challenge.

@dtheobald, did we previously challenge the de-REGISTER?

@rkd-msw, do you know how your changes might have affected this flow?

**Comment by dtheobald** [comment]
@mirw - Yes, de-registrations were previously challenged (see below).
![image](https://cloud.githubusercontent.com/assets/6430927/14953065/954e2e84-102b-11e6-8faa-d81795e2e26d.png)
I've put that SAS trace in the diags area too.

**Comment by mirw** [comment]
The only difference I can see between the traces is that in the working trace the Server-Name on the MAR matches that on the UAA, while on the failed trace the Server-Name on the MAR is different.

That does tie in with one of @rkd-msw's changes (which, I believe, changes the Server-Name), except that the difference actually seems to be between how `=` is encoded.  In the failed case, the UAA's Server-Name is `sip:scscf.sprout.x.dat.core.clearwater.metaswitch.com:5054;transport%3DTCP` (note the `%3D`).

**Comment by mirw** [comment]
@eleanor-merry, please can you take a look?  (I mis-spoke when I said these were @rkd-msw's changes.)

**Comment by eleanor-merry** [comment]
Hi @dtheobald - just to check, this is on a system that's been upgraded from CCv8-9 using the new upgrade procedure, and the subscriber has registered before the upgrade? (I think I see the issue, but I want to check the deployment status)

**Comment by dtheobald** [comment]
@eleanor-merry No, this was on a system that was freshly deployed from new appliances containing that commit. Those traces are from the "Basic registration" Quaff test.

Another clue might be that the same test works on a system using homestead-prov instead of an HSS.

**Comment by eleanor-merry** [comment]
@dtheobald sorry, I should have passed this back to you for retest

**Comment by rkd-msw** [comment]
@eleanor-merry - is https://github.com/Metaswitch/sprout/pull/1433 the PR that fixed this?
