### ISSUE TITLE
scscf_test.cpp accidentally uses the SP::Message object defined in bono_test.cpp

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/sprout#1429]
Both scscf_test.cpp and bono_test.cpp define and use an SP::Message class. Unfortunately, scscf_test actually uses bono_test's version of SP::Message. This is presumably because at link time the bono_test version of the object gets picked (effectively randomly, although actually probably actually based on some heuristic like alphabetical order or order in a Makefile or something). It's a little bit surprising that at some point the build doesn't fail because we've got multiple versions of the same object, but perhaps that isn't a thing.

We have a lot of test fixtures that use very similar versions of the Message class, and they're inconsistently defined (some are defined in an SP namespace, some are defined in the test fixture class). Ideally we should almost certain have a single all-purpose common Message class across the UTs, but that is beyond the scope of this issue.

Incidentally, what even is the namespace SP supposed to be?

**Comment by graemerobertson** [comment]
@Tom-Rees is fixing this I believe

**Comment by graemerobertson** [comment]
@Tom-Rees @AlexHockey Let's close this issue since it explicitly states that trying to commonsing the Message class is beyond the scope of this issue (and we're already tracking it elsewhere) - agreed?

**Comment by Tom-Rees** [comment]
Sounds good to me - Alex, feel free to re-open if you disagree.
