### ISSUE TITLE
Sprout crashed while running MMTEL TAS traffic at 50 cps

### ISSUE THREAD

**Issue by tcaterisano** [Metaswitch/sprout#1436]
#### Symptoms

Noticed a sig 11 crash on Sprout while running a traffic soak test with all subs enabled with MMTEL features.

```
#2  0x00007f6302f72182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007f630191947d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f62fa4b2700 (LWP 5990)):
#0  0x00007f63018dfb99 in waitpid () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f63018652e2 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004e0753 in Logger::backtrace (this=0x1d7f1f0, data=<optimized out>) at ../modules/cpp-common/src/logger.cpp:318
#3  0x0000000000594f9d in Log::backtrace (fmt=fmt@entry=0x735938 "Signal %d caught") at ../modules/cpp-common/src/log.cpp:185
#4  0x00000000005edb1c in signal_handler (sig=11) at main.cpp:1184
#5  <signal handler called>
#6  0x00007f63018b6ffe in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f63021bae30 in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f63021bb48c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00000000004e36e1 in construct<std::basic_string<char>, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (__p=<optimized out>, this=0x7f62fa4b1d80) at /usr/include/c++/4.8/ext/new_allocator.h:120
#10 _S_construct<std::basic_string<char>, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (__p=<optimized out>, __a=...) at /usr/include/c++/4.8/bits/alloc_traits.h:254
#11 construct<std::basic_string<char>, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (__p=<optimized out>, __a=...) at /usr/include/c++/4.8/bits/alloc_traits.h:393
#12 std::vector<std::string, std::allocator<std::string> >::_M_emplace_back_aux<std::string const&> (this=this@entry=0x7f62fa4b1d80) at /usr/include/c++/4.8/bits/vector.tcc:408
#13 0x00000000005d328d in push_back (__x="sprout\000%0\000\000\000\000\000\000\000!\220\000\000\000\000\000\000\300o\334\001\000\000\000\000\320\202\275\002", '\000' <repeats 20 times>, "ion: Fatal - Authentication enabled, but no Homestead server specified in /etc/clearwater/config. @@Cause: The hs_hostname was not set in the /e"..., this=0x7f62fa4b1d80) at /usr/include/c++/4.8/bits/stl_vector.h:911
#14 AlarmState::issue (this=0x2bea8e8) at ../modules/cpp-common/src/alarm.cpp:69
#15 0x00000000005d3562 in reraise_last_state (this=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:103
#16 AlarmManager::reraise_alarms (this=0x1dc3c20) at ../modules/cpp-common/src/alarm.cpp:257
#17 0x00000000005d3649 in AlarmManager::reraise_alarms_function (data=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:225
#18 0x00007f6302f72182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007f630191947d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f6304e53800 (LWP 5971)):
#0  0x00007f6302f78f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f6302f74657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f6302f74480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00000000005d0fd7 in AlarmManager::~AlarmManager (this=0x1dc3c20, __in_chrg=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:202
@
```
#### Impact

Some call failures
#### Release and environment

Latest CCV9 + Latest OC TAS

astaire                        9.0.0-1-1.0.0-160506.123137
astaire-libs                   9.0.0-1-1.0.0-160506.123137
chronos                        9.0.0-1-1.0.0-160506.123137
clearwater-cluster-manager     9.0.0-1-1.0.0-160506.123137
clearwater-config-manager      9.0.0-1-1.0.0-160506.123137
clearwater-diags-monitor       9.0.0-1-1.0.0-160506.123137
clearwater-etcd                9.0.0-1-1.0.0-160506.123137
clearwater-infrastructure      9.0.0-1-1.0.0-160506.123137
clearwater-log-cleanup         9.0.0-1-1.0.0-160506.123137
clearwater-memcached           9.0.0-1-1.0.0-160506.123137
clearwater-monit               9.0.0-1-1.0.0-160506.123137
clearwater-net-snmp            9.0.0-1-1.0.0-160506.123137
clearwater-queue-manager       9.0.0-1-1.0.0-160506.123137
clearwater-snmp-alarm-agent    9.0.0-1-1.0.0-160506.123137
clearwater-snmpd               9.0.0-1-1.0.0-160506.123137
clearwater-snmp-handler-astaire 9.0.0-1-1.0.0-160506.123137
clearwater-socket-factory      9.0.0-1-1.0.0-160506.123137
clearwater-tcp-scalability     9.0.0-1-1.0.0-160506.123137
cwc-infrastructure             9.0.0-1-1.0.0-160506.123137
memcached-clearwater           1.6.00-0+9.0.0.1.1.0.0+0.5
metaswitch-core-sprout         9.0.0-1-1.0.0
sprout                         9.0.0-1-1.0.0-160506.123137
sprout-base                    9.0.0-1-1.0.0-160506.123137
sprout-bgcf                    9.0.0-1-1.0.0-160506.123137
sprout-icscf                   9.0.0-1-1.0.0-160506.123137
sprout-libs                    9.0.0-1-1.0.0-160506.123137
sprout-mmtel-as                9.0.0-1-1.0.0-160506.123137
sprout-scscf                   9.0.0-1-1.0.0-160506.123137
#### Steps to reproduce

Run traffic soak at 50 cps with CCV9+TAS and all subs enabled for MMTEL services

**Comment by rkd-msw** [comment]
Ellie - the stack trace looks like https://github.com/Metaswitch/cpp-common/issues/521 which you fixed under https://github.com/Metaswitch/cpp-common/issues/526. Can you sanity-check my reasoning, and close if you agree it looks fixed?

**Comment by eleanor-merry** [comment]
Yup, I agree
