### ISSUE TITLE
HTTP connection pool would stop TCP connect latency from affecting the call path

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/sprout#144]
In some cloud environments we have seen significant delays (towards 500ms) setting up TCP connections - that is a delay between SYN and SYN,ACK.  We are speculating that the delay is something to do with the hypervisor or security group architecture, but don't currently have more details.

This causes problems for Sprout when it is recycling HTTP connections to Homer or Homestead.  We currently have the connect time set low because any delay in connecting will impact the latency of the system.  It will also affect how quickly we try to connect to an alternative Homestead/Homer instance.

We therefore need to move this connection recycling processing outside of the main SIP message processing path (in the same way we do with SIP connections from Bono to Sprout).  Unfortunately this isn't trivial to do using libcurl.

**Comment by rkd-msw** [comment]
I didn't complete the pool mentioned above (stats turned out harder than I expected IIRC) - but we haven't seen this kind of latency in EC2 recently, and I think that kind of latency would be unacceptable in most use-cases, so I think this is now low priority.

**Comment by rkd-msw** [comment]
Also, this may not be such a good idea at all - c.f. https://github.com/Metaswitch/sprout/issues/548, where we create a pool of memcached connections in advance but they're all unusable by the time we need them.

**Comment by rkd-msw** [comment]
On the basis of the concern above about #548 , I'm closing this issue.
