### ISSUE TITLE
Sprout depends on a specific version of Boost

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/sprout#145]
Sprout depends on a specific version of Boost, which may not be available in all clouds.  The recommended method is to depend on libboost-dev, which is supposed to then work out what versions to pull in.

We temporarily fixed this by changing dependency to libboost-dev, but needs more thought.  May make sense to include the appropriate libraries in our own packages to simplify things and reduce chance for incompatibilities.  Alternatively we could just statically link the three boost libraries we use at build time and remove the dependency all together.

**Comment by rkd-msw** [comment]
I think this is probably a stale issue - depending on Boost 1.46.1 hasn't caused any incompatibilities. We might want to change our Boost version if we move to support 14.04, but that will just fall naturally out of the test-and-fix work there.
