### ISSUE TITLE
Disable the ability to configure the chronos connection

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/sprout#1463]
#### Symptoms
I can disable Chronos by setting chronos_hostname to "" in the config. This means that the chronos_connection object is NULL. However, the authentication module and the subscriber data manager use the ChronosConnection without checking it's NULL.

**Comment by richardwhiuk** [comment]
As discussed with @eleanor-merry and @mirw, we agreed that we don't believe it's valid to configure it to be null, and in the past we've tried to remove the ability to configure the chronos connection without fully removing it. We'll complete the work to do that.
