### ISSUE TITLE
building sproutlets via the plugins directory is currently broken

### ISSUE THREAD

**Issue by benritchie** [Metaswitch/sprout#1473]
Broken by the changes to add RPM support, under 183d227cd96b411998e952d5ee1ba2931e9c3e17
If you clone the demo greeter project into the plugins directory, and run make all in the plugin sub-directory, you get:
ubuntu@ben-VirtualBox:/opt/clearwater/sprout/plugins/bgcf$ make build
/opt/clearwater/sprout/build-infra/cw-deb.mk:66: build-infra/cw-pkg.mk: No such file or directory
make: *** No rule to make target `build-infra/cw-pkg.mk'. Stop.
ubuntu@ben-VirtualBox:/opt/clearwater/sprout/plugins/bgcf$ 

Issue appears to be that cw-deb.mk includes a relative reference on line 66 "include build-infra/cw-pkg.mk".  that fails if run from a directory other than the root directory.  

I can take a look at fixing later, although if any makefile expert can see how this should work, and wants to jump in, feel free :)

**Comment by mirw** [comment]
I suspect the fix is to add change `include build-infra/cw-pkg.mk` to `include $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/cw-pkg.mk`.  Worth a shot?
