### ISSUE TITLE
Errors from SNMP agent at startup

### ISSUE THREAD

**Issue by dimbleby** [Metaswitch/sprout#1475]
Like this, in `/var/log/sprout/sprout_current.txt`:

```
07-07-2016 10:12:52.051 UTC Error (Net-SNMP): read_config_store open failure on /var/lib/snmp/sprout.conf
07-07-2016 10:12:52.051 UTC Error (Net-SNMP): read_config_store open failure on /var/lib/snmp/sprout.conf
07-07-2016 10:12:52.051 UTC Error (Net-SNMP): read_config_store open failure on /var/lib/snmp/sprout.conf
```

(In the Robocall service we're monitoring for error logs.  So although I guess this is likely benign, that's why we've noticed it).

[This thread](https://sourceforge.net/p/net-snmp/mailman/net-snmp-coders/thread/20120413090654.3d25672f@freesnmp.com/) suggests that this is about what user the snmp agent is running as.  

Since this log is coming from the sprout process I suppose it's running as the `sprout` user, who probably doesn't have permission to do anything in `/var/lib/snmp`.

Presumably either the permissions should be changed, or the SNMP agent should somehow be directed to use some other file.

**Comment by johadalin** [comment]
Trying to figure out how to prioritise this appropriately. 
Does this cause any symptoms other than the error logs? Or is it simply that it is causing log spam?

**Comment by dimbleby** [comment]
From our point of view this is only spam.

Of course It's possible that this is symptomatic in ways that we all haven't noticed yet - presumably the SNMP agent has some reason for wanting to write to that file.

**Comment by johadalin** [comment]
OK. Putting this as low priority for now, but if anyone does see other symptoms, or if the log spam is causing trouble, we can upgrade it later

**Comment by eleanor-merry** [comment]
Fixed by linked PR
