### ISSUE TITLE
Log spam in non-GR deployment

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#1503]
#### Symptoms

Create a non-GR deployment (on Aarch64, as it turns out, but I don't think that's relevant).  This creates an `/etc/clearwater/remote_cluster_settings` file containing `servers=` (with no servers).

See the following log in syslog on start-up:

```
Aug  8 13:35:34 localhost sprout[21617]: 1006 - Description: The memcached cluster configuration has been updated. There are now 0 nodes in the cluster. @@Cause: A change has been detected to the /etc/clearwater/remote_cluster_settings configuration file that has changed the memcached cluster. @@Effect: Normal. @@Action: None.
```

See the following logs in `/var/log/sprout/sprout_current.txt` on start-up:

```
08-08-2016 14:18:36.172 UTC Warning main.cpp:1894: Remote cluster settings file '/etc/clearwater/remote_cluster_settings' does not contain a valid set of servers
```

See the following logs in `/var/log/sprout/sprout_current.txt` frequently (on every registration?):

```
23-02-2015 13:23:42.943 UTC Error memcachedstore.cpp:709: Failed to read data for reg\\sip:2010029904@xxx.test from 0 replicas
23-02-2015 13:23:42.943 UTC Error registrar.cpp:260: Failed to get AoR binding for sip:2010029904@xxx.test from store
```

#### Impact

Spurious serious warnings on start-up, and log spam during operation.

#### Release and environment 

Custom build from https://github.com/Metaswitch/sprout/tree/7800335bf98bec7e88eef0f3798977c8fbf19660, running on OpenStack on Aarch64

#### Steps to reproduce

Deploy a non-GR deployment and check logs.

**Comment by mirw** [comment]
Tagging as medium priority because of the per-registration/per-call log spam.

**Comment by richardwhiuk** [comment]
Sprout creates objects representing a remote `MemcachedStore`, and then a remote `SubscriberDataManager`, if `--remote-memstore` is specified.

`--remote-memstore` is always specified, creating an empty `/etc/clearwater/remote_cluster_settings`, as we want to be able to updated the remote cluster settings using a reload as opposed to a restart.

In a GR deployment, if the cluster is configured without any servers, clearly warning is appropriate. However, in a non-GR deployment, clearly this is just log and alarm spam....

**Comment by richardwhiuk** [comment]
This is fixed https://github.com/Metaswitch/sprout/pull/1431
