### ISSUE TITLE
The --default-tel-uri-translation option is marked as requiring an argument, but doesn't need one

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1511]
#### Symptoms

The new ```default-tel-uri-translation``` option is marked in source as requiring an argument, but neither needs one nor is given one in sprout's init.d script. As such, in my configuration sprout doesn't get configured for SAS properly because the ```--sas``` option gets eaten by the ```default-tel-uri-translation``` option since it immediately follows it on sprout's command line.

I've temporarily made the following source change (in main.cpp) since this is a blocking issue:
```
@@ -181,7 +181,7 @@ const static struct pj_getopt_option long_opt[] =
   { "enum",                         required_argument, 0, 'E'},
   { "enum-suffix",                  required_argument, 0, 'x'},
   { "enum-file",                    required_argument, 0, 'f'},
-  { "default-tel-uri-translation",  required_argument, 0, OPT_DEFAULT_TEL_URI_TRANSLATION},
+  { "default-tel-uri-translation",  no_argument,       0, OPT_DEFAULT_TEL_URI_TRANSLATION},
   { "enforce-user-phone",           no_argument,       0, 'u'},
   { "enforce-global-only-lookups",  no_argument,       0, 'g'},
   { "reg-max-expires",              required_argument, 0, 'e'},
```

#### Impact

No SAS events from sprout

#### Release and environment 

release-104

**Comment by mirw** [comment]
@rkd-msw, please can you take a look?

**Comment by rkd-msw** [comment]
Whoops - missed that in my testing because I was focusing in the new case I'd introduced (where this behaviour is disabled and the option isn't present). Fixed under https://github.com/Metaswitch/sprout/pull/1512.
