### ISSUE TITLE
'error' log for dull signaling flow

### ISSUE THREAD

**Issue by dimbleby** [Metaswitch/sprout#1531]
#### Symptoms
This log:

    09-09-2016 01:28:03.706 UTC Error basicproxy.cpp:402: Rejecting CANCEL request with 481 status code

#### Impact
On our server we have set up alerts for error logs from sprout, in the expectation that error logs indicate things that we might care about.  

This looks as though it's some fairly normal window condition in the signaling that I really don't need to be alerted about.

Suggest that this log should be a warning at most, probably only info.

#### Release and environment 
Recent sprout code.

#### Steps to reproduce
I don't have trace but, presumably, just send in a CANCEL for a call that doesn't exist any more.

**Comment by richardwhiuk** [comment]
In general, I'm not convinced that any error that we are proxying should be an error level diagnostic.

**Comment by dimbleby** [comment]
We get enough of these that I'm inclined to do something about it, at least in our copy of sprout.

Would you take a pull request that downgraded this log to a WARNING?  

If you intend eventually to do something not very much more complicated I'd probably be willing to do that instead.

If you intend eventually to do something that _is_ very much more complicated - then how about taking the downgrade-to-warning fix as a stopgap?

**Comment by mirw** [comment]
I think this should be downgraded to TRC_DEBUG.  I wondered whether we should SAS log it, but I think that's already covered by other SAS events.  I'll get this merged.

**Comment by dimbleby** [comment]
super, thanks!
