### ISSUE TITLE
memcached data not resynced on adding Sprout node

### ISSUE THREAD

**Issue by sebrexmetaswitch** [Metaswitch/sprout#1552]
#### Symptoms
Adding a sprout node to an existing Sprout cluster by changing the cluster_settings file and reloading Astaire doesn't copy across memcached data to the new Sprout node.
The Astaire logs show:

> 30-09-2016 09:03:26.542 UTC Debug signalhandler.h:161: Signal 1 raised
> 30-09-2016 09:03:26.542 UTC Debug astaire.cpp:118: Reloading memcached config
> 
> [...]
> 
> 30-09-2016 09:03:26.543 UTC Debug memcachedstoreview.cpp:259: New view -
> 
> [...]
> 
> 30-09-2016 09:03:26.543 UTC Status memcached_backend.cpp:158: Finished preparing new view, so flag that workers should switch to it
> 30-09-2016 09:03:26.543 UTC Debug astaire.cpp:161: View has been updated - resync required
> 30-09-2016 09:03:26.544 UTC Debug astaire.cpp:818: Found tag - memcached is up-to-date
> 30-09-2016 09:03:26.544 UTC Debug astaire.cpp:465: Start resync operation
>
> [...]
> 
> 30-09-2016 09:03:26.544 UTC Info astaire.cpp:470: No resyncing required

#### Impact
If the sprout node with the stored data goes down, data is lost.

#### Release and environment 
Current dev branch

#### Steps to reproduce
Start with single Sprout node with registered subscribers.
Bring up a new Sprout node and attempted to add it to the memcached cluster manually by, on each:
 - disabling config manager
 - editing the cluster_settings file to have both nodes in the new_servers line (in addition to the existing node in the servers line)
 - reloading Sprout to use the new cluster settings: `sudo /usr/share/clearwater/bin/reload_memcached_users`
 - resycincing memcached:
`sudo service astaire reload`
`sudo service astaire wait-sync`

Then kill memcached on node 1 and the subs can't make calls

**Comment by AME2** [comment]
As it is the reproduction process described above does result in successful calls being made. However if the Sprout process is turned off on the second node as it rejoins the cluster then calls do fail, I am currently investigating why this is.
