### ISSUE TITLE
Deregistration in GR deployment causes sprout to send 2 deregistration HTTP requests to homestead

### ISSUE THREAD

**Issue by sebrexmetaswitch** [Metaswitch/sprout#1555]
#### Symptoms

For a deregistration in a 2 site deployment, sprout sends 2 deregistration HTTP requests to homestead.
The second of these correctly receives a 400 Bad Request, triggering Sprout to log an error:

`04-10-2016 14:25:50.967 UTC Error httpclient.cpp:615: cURL failure with cURL error code 0 (see man 3 libcurl-errors) and HTTP error code 400`
`04-10-2016 14:25:50.968 UTC Error hssconnection.cpp:617: Could not get subscriber data from HSS`
#### Impact

This is benign, but causes a Sprout error log and a scary-sounding "Fatal HTTP error encountered" log in SAS.
#### Release and environment

Latest dev release
#### Steps to reproduce

Spin up a 2-site deployment, and register then deregister a subscriber.

**Comment by sebrexmetaswitch** [comment]
This is caused by the fact that the `write_to_store` function in registrar.cpp is called once per site, and that function is what triggers the HTTP request

**Comment by sebrexmetaswitch** [comment]
loosely related to #552

**Comment by MatMeredith** [comment]
Fixed by PR #1635
