### ISSUE TITLE
Sprout will incorrectly fail AKA authentication if the RES/XRES contains an 0x00 byte

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1599]
#### Symptoms

I added an AKAv1 live test, and noticed it intermittently failing (with my authenticated REGISTER being rejected with a 403 Forbidden). A SAS trace is at \\ad\csd\bigfiles\clearwater\issue-attachments\.

Looking at this SAS trace, the SIP-Authorization in the MAA is 0x346667c3e9200037 - i.e. one of the bytes is 0x00. I added some logging to my test script, which confirms that the failures happen when (and only when) the RES contains a zero byte.

#### Impact

This causes a REGISTER to be rejected with a 403 when it happens, and https://tools.ietf.org/html/rfc3261#section-21.4.4 says that 403 means a request SHOULD NOT be repeated, so a subscriber might lose service when this happens.

There are 8 bytes in the RES, and any one of them being 0x00 causes this, so this will happen on (1/256 + 1/255 ... + 1/249) of REGISTERs - i.e. this will make about 3.17% of AKAv1 REGISTERs fail. (That matches up with the frequency of test failures I'm seeing).

#### Release and environment 

Quilava release, on VMware (but unlikely to be specific to either). I'm using the vmware.obu-enfield.test deployment for this testing.

#### Steps to reproduce

Attempt AKAv1 registration with a RES that includes 0x00. (This could probably be reproduced in UT, but RES isn't easy to control live, so you'd just need to REGISTER repeatedly.)

**Comment by rkd-msw** [comment]
Notes on my approach here:

* As part of automating an AKAv1 test, I ran it repeatedly, and noticed that it sometimes failed with a 403 (but would succeed again on the next go, with the same user, the same credentials, and without having reset the sequence number). I decided to dig into this.
* SAS isn't very helpful, just saying `Authentication failed as the challenge response was incorrect (wrong password or authentication realm)`. This is probably reasonable - both for security reasons and because it's hard to see what better diags we could provide here.
* SAS does show the XRES from the HSS (in the SIP-Authenticate field of the MAA), so I enhanced my test client to also add the RES it calculated as a header so I could compare them, and make sure my test client and the HSS weren't doing the AKA calculation differently.
* The RES and XRES matched up, but when inspecting them, I saw that one of the bytes was zero. This made me suspicious, because I knew that `\0` ends a string in C, so that seemed like a plausible bug.
* To confirm that hypothesis, I enhanced my test client to print out a log when the RES had a zero byte, ran the tests repeatedly, and confirmed that I got a failure if and only if that happened.
* It wasn't clear whether Sprout or my test client was handling the NULL byte incorrectly in its calculations, so I checked the Sprout code and saw https://github.com/Metaswitch/sprout/blob/190cf993a5629fffeb607d69ac3f49e9e4cca21d/src/authentication.cpp#L318, where we treat the XRES as a NULL-terminated C string. (If I'd been less familiar with Sprout, I might have checked my test client's code, or raised the bug with a caveat that I wasn't sure it wasn't a client bug.)
* I also wondered about other similar bugs, and I spotted https://github.com/Metaswitch/sprout/blob/190cf993a5629fffeb607d69ac3f49e9e4cca21d/src/authentication.cpp#L496, where `unsigned char* digest` might include NULL bytes but we use the std::string constructor that assumes it's NULL-terminated.

**Comment by richardwhiuk** [comment]
Rob, I've fixed both of these in the attached pull request, so this is back with you to retest.

**Comment by rkd-msw** [comment]
As discussed by email, I don't think this is in a state where I can retest because you haven't given me the updated build (either as new OVAs or as a patch). Next action is with you, or someone else on the dev team, so reassigning.

**Comment by rkd-msw** [comment]
Confirmed fixed in 1.0-cc-10.0.0-20161205-~255.00.0-161205.102515.
