### ISSUE TITLE
When one of two Sprout nodes is down, some REGISTERs fail

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1607]
#### Symptoms

I had a deployment with one working Sprout node, one dead Sprout node (on which I'd run 'service sprout stop' as it failed to cluster) and two Homestead nodes. I was sending REGISTER traffic into the working Sprout node's I-CSCF port.

There were intermittent failures, an example SAS trace of which is at \\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1607. In this trace, it looks like:

* we reached the I-CSCF
* it attempted to forward the REGISTER to `sip:scscf.sprout.stress.clearwater.test;transport=TCP`, which it resolved first to the dead Sprout node, sprout-2 (per the 'The SRV lookup has returned for target: _sip._tcp.scscf.sprout.stress.clearwater.test' log at 20:34:33.971)
* that node isn't up, but I'd expect us to be redundant and for sprout-1 to just act as the S-CSCF here
* (at this point, some processing happens that I can't quite decode from the SAS trace)
* instead, we send back a 504 Server Timeout back to the P-CSCF
* ...but for some reason we then send a GET to Homestead to trigger a Multimedia-Auth-Request 15ms after sending that 504

#### Impact

The REGISTER fails, causing the affected subscriber to lose service. This happens rarely, I think because we blacklist the dead Sprout node for 30 seconds after seeing one such failure.

#### Release and environment 

CC-sprout-10.0.0-20161116-~255.00.0.ova

#### Steps to reproduce

With one Sprout node down but still in DNS, run REGISTER stress.

**Comment by rkd-msw** [comment]
I've also put a working REGISTER flow in that directory for comparison, as some of the SAS logs which suggest something going wrong (e.g. "The Sproutlet selection process hasn't found any suitable Sproutlets to process this request") seem to appear in both - which is probably worth a separate diagnostics bug.

**Comment by MatMeredith** [comment]
Hi Rob.    You say "This happens rarely, I think because we blacklist the dead Sprout node for 30 seconds after seeing one such failure.".   Does that mean that you were seeing this failures regularly -- e.g. once every 30 seconds or so, rather than this being e.g. a one-off?

You saved off the SAS trace, but I don't think we have any logs.   If it's reproducible, can you repro and provide logs please (just normal error level logging is fine in the first instance)?   Thanks.

**Comment by rkd-msw** [comment]
That's right - I don't think this was a one-off. I'll try and repro today.

**Comment by rkd-msw** [comment]
OK, fresh SAS trace and diags bundle from sprout-1 attached.

**Comment by rkd-msw** [comment]
FTR I've hit this about 3 times in 50,000 REGISTERs.

**Comment by mirw** [comment]
It looks like the following are the key logs:

```
20-12-2016 18:05:50.025 UTC Error pjsip: tcpc0x7fcdb81d TCP connect() error: Connection refused [code=120111]
20-12-2016 18:05:50.025 UTC Warning pjsip: tsx0x7fcdb81a3 Failed to send Request msg REGISTER/cseq=1 (tdta0x7fcdb8211230)! err=120032 (Broken pipe)
```

**Comment by mirw** [comment]
Interestingly, we also see:

```
20-12-2016 18:07:20.013 UTC Warning pjsip: tsx0x7fcd68003 Failed to send Request msg REGISTER/cseq=1 (tdta0x7fcd6832d710)! err=120032 (Broken pipe)
20-12-2016 18:07:20.013 UTC Error pjsip: tcpc0x7fcd681f TCP connect() error: Connection refused [code=120111]
```

These are the same logs in the opposite order.  I'd originally expected them to be on the same thread, but maybe they're not?

**Comment by mirw** [comment]
Hmm... I'm suspicious of the comment in `PJUtils::on_tsx_state` (which I think I wrote a long time ago):

```
            // Copy across the destination information for a retry and try to
            // resend the request.  Note that we ignore the return code for
            // the send - it will always call on_tsx_state on success or
            // failure, and that will recover.
            PJUtils::set_dest_info(tdata, sss->servers[sss->current_server]);
            (void)pjsip_tsx_send_msg(retry_tsx, tdata);
```

Note the comment that `pjsip_tsx_send_msg` will always call `on_tsx_state`.

In both `BasicProxy::UACTsx::send_request` and `BasicProxy::UACTsx::retry_request`, we call `pjsip_tsx_send_msg` and then look at the return code and say that we're not retrying if it returned failure.  However, I wonder if it might have called `on_tsx_state` in the meantime, i.e.

*   the I-CSCF Sproutlet tries to forward on the REGISTER to the S-CSCF
*   this calls into `BasicProxy::UACTsx::send_request`, first picking the failed S-CSCF
*   `BasicProxy::UACTsx::send_request` calls into `pjsip_tsx_send_msg`
*   this fails, and calls the `on_tsx_state` callback synchronously
*   this calls into `BasicProxy::UACTsx::on_tsx_state` and from there into `BasicProxy::UACTsx::retry_request`, which retries the REGISTER to the live S-CSCF
*   the stack unwinds and `pjsip_tsx_send_msg` returns an error code to `BasicProxy::UACTsx::send_request`
*   `BasicProxy::UACTsx::send_request`  calls into the `on_client_not_responding` callback, which ends up passing a 503 response into the I-CSCF Sproutlet
*   the I-CSCF Sproutlet continues its processing by querying Homestead, even though there's an outstanding REGISTER transaction.

I suspect the first thing to try is reading the code in `pjsip_tsx_send_msg` to confirm the behavior alluded to above - if true, it seems we should remove some (if not all) checks on `pjsip_tsx_msg_msg` calls.

**Comment by mirw** [comment]
@MatMeredith, I think you own this issue - are you OK to run with this?  Feel free to grab me to discuss tomorrow.

**Comment by MatMeredith** [comment]
So I've started looking at this again...

If I've read the code right then it looks like pjsip_tsx_send_msg can result in a synchronous on_tsx_state callback and then a failure return code.

```
tsx_send_message
-	2086         tsx_set_status_code(tsx, PJSIP_SC_TSX_TRANSPORT_ERROR, &err);
-	2087         tsx_set_state( tsx, PJSIP_TSX_STATE_TERMINATED,
-	2088                        PJSIP_EVENT_TRANSPORT_ERROR, NULL );

-	-	tsx_set_state
-	-	1194     /* Inform TU about state changed. */
-	-	1195     if (tsx->tsx_user && tsx->tsx_user->on_tsx_state) {
-	-	1196         pjsip_event e;
-	-	1197         PJSIP_EVENT_INIT_TSX_STATE(e, tsx, event_src_type, event_src,
-	-	1198                                    prev_state);
-	-	1199         (*tsx->tsx_user->on_tsx_state)(tsx, &e);
-	-	1200     }

That's as far as I've got so far.   I'd quite like to look and see what happens differently when we retry and it succeeds -- perhaps the failure to send the message isn't synchronous in that case?

Just removing the checking on the pjsip_tsx_send_msg return code doesn't immediately look safe.   Presumably if multiple Sprout nodes are down we could get recursive re-entry into on_tsx_state which doesn't immediately look like it will turn out well...

**Comment by mirw** [comment]
Yes, if you retry and it succeeds (or it fails, but asynchronously), you just get the on_tsx_state function call.  This is why it is so confusing that in the case where it fails synchronously you get both!  (Although I've always accepted that this is just how PJSIP works, I now wonder whether it's actually a bug.)

On your last point, bear in mind we have quite a low limit on the number of peers we will retry, so although we could recursively re-enter on_tsx_state, you can't do it many times.

**Comment by MatMeredith** [comment]
So, I've thought about this a bit more and discussed further with MIRW.   FTR, and (mostly summarising the trail above).

-	When a Sprout is down, sometimes we retry successfully and it all works as expected, other times we hit this issue.  In both cases...
o	The first REGISTER fails.
o	The retry **would** succeed (asynchronously, given the chance)
The difference is in how the first REGISTER fails…
o	When it goes wrong (we believe) the first REGISTER fails synchronously: we call pjsip_tsx_send_msg, it calls back into on_tsx_state callback saying that the tsx has been terminated (which correctly causes us to retry) and then we get a failed return code from the original pjsip_tsx_send_msg (which causes us to decide we can’t retry)
o	In the case where it all works correctly, for some reason (presumably the TCP connection is in a different state?) the original REGISTER fails asynchronously, resulting in a successful return code from pjsip_tsx_send_msg (no effect) followed by an on_tsx_state saying that the tsx has been terminated (which correctly causes us to retry).

The fix then is to not take action on a failure return code from pjsip_tsx_send_msg, and rather assume that in the case of failure, we either will already have had, or we will subsequent get a on_tsx_state_callback telling us that the tsx has been terminated.

Note that I've read through the PJSIP processing and am reasonably confident that this is a safe assumption.   I was concerned that it was possible to fail synchronously **without** calling on_tsx_state_callback here (https://github.com/Metaswitch/pjsip-upstream/blob/cfd114723c6622b7828484b251f6586e085674cb/pjsip/src/pjsip/sip_transaction.c#L2120-L2121) but in that case transaction state is already terminated (and on_tsx_state_callback will have been called when it moved to that state).

Other points from discussion with MIRW...
- We don't think this will be easy to test / repro in Sprout UT -- we'd have to enhance the fake TCP connection object to support simulating failure but aren't convinced that it's worth it.
- We think the priority here is getting a quick fix into Rob to confirm that our theory is right and that this does fix his issue.

I've started (like 10 minutes work) to code a fix on the mgm_issue_1607 branch in Sprout.   This might be sufficient to build a patch and get it to Rob to try out.  Still to do:
- Look for other cases where we call pjsip_tsx_send_msg and act on a failed return code.
- In particular I'm a bit worried about what happens after calling it here.  https://github.com/Metaswitch/sprout/blob/05b27288197791ce1a6853f460a3e6fc10838974/src/basicproxy.cpp#L2071   In particular we need to think through this happening recursively.
  - pjsip_tsx_send_msg fails synchronously -> on_tsx_state_callback -> BasicProxy::retry_request -> pjsip_tsx_send_msg -> etc. with perhaps multiple synchronous failures terminating in any of:
    - no more servers to try
    - asynchronous failure
    - asynchronous success.
I don't have a handle on what happens with the multiple transactions that will get created here, bound / unbound to / from the UACTsx, when they will all get cleaned up / destroyed etc.

**Comment by johadalin** [comment]
#1688 Should resolve this issue for most cases.
#1687 covers the use of `pjsip_tsx_send_msg` in `retry_request`, but we think this is going to be a much rarer possibility to hit, and also less likely to be problematic. I've also had a look through, and can't see any other locations where we use the status returned by `pjsip_tsx_send_msg`, other than one occasion where we write a log if it fails. 

Passing back to @rkd-msw to do a proper stress-run system test to see if the fix in #1688 does solve the issue, or if there is more complication to this than we've found so far.

**Comment by rkd-msw** [comment]
As discussed, it would be great to have a temporary TRC_WARNING, so i can distinguish "didn't hit this bug" from "hit this bug and your fix worked".

**Comment by rkd-msw** [comment]
Looks good! Running stress on 10.0.0-170126-~255.00.0-170126.020419, I see this log:

`30-01-2017 08:36:32.010 UTC Warning basicproxy.cpp:1707: pjsip_tsx_send_msg synchronously returned failure status code`

but I don't see a corresponding call failure.

The log you added was useful, by the way - I initially retested this wrongly (sending traffic to the S-CSCF port not the I-CSCF port) and not seeing that log tipped me off that something was wrong.

Back to you to back out the temporary warning log, then OK to close.
