### ISSUE TITLE
Number-related BGCF logs say "routing directly", but that concept doesn't make sense

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1611]
#### Symptoms

In the attached off-net routing SAS trace, at 2016-11-27 17:13:46.315, the log says `BGCF lookup for number "+22233" failed - routing directly`.

"routing directly" makes sense for domains (where you can do standard SIP routing on the domain), but not for numbers.

I've seen this in two cases:

- without a wildcard route configured, in which case the call wasn't routed directly, it was rejected with a 404
- with a wildcard route configured, in which case that route was used (which still isn't "routing directly")

#### Impact

Misleading diagnostics.

#### Release and environment 

`1.0-cc-10.0.0-20161116-~255.00.0-161116.175811` on VMware.

#### Steps to reproduce

Dial a phone number which is routed to the BGCF, but for which there is no matching number rule.

**Comment by rkd-msw** [comment]
Diags at \\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1611

**Comment by sebrexmetaswitch** [comment]
I think the fix here is just to remove the unhelpful "routing directly" line from the SAS logs.

**Comment by sebrexmetaswitch** [comment]
I've done that, should be in the latest sas resources

**Comment by rkd-msw** [comment]
Yep, fixed.
