### ISSUE TITLE
enum.json ordering requirements are unintuitive

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1619]
#### Symptoms

I set up an enum.json file like this:

```
{
  "number_blocks": [
    {
      "regex": "!(^.*$)!tel:\\1;npdi!",
      "prefix": "+22",
      "name": "+22 Numbers"
    },
    {
      "regex": "!(^.*$)!tel:\\1;extra-parameter-here;npdi!",
      "prefix": "+2223",
      "name": "+2223 Numbers"
    }
  ]
}
```

When I made a call to +22233 (Trace1.sas), the `extra-parameter-here` parameter wasn't added by ENUM, suggesting that it matched the less-specific +22 prefix.

I then reordered the file:

```
{
  "number_blocks": [
    {
      "regex": "!(^.*$)!tel:\\1;extra-parameter-here;npdi!",
      "prefix": "+2223",
      "name": "+2223 Numbers"
    },
    {
      "regex": "!(^.*$)!tel:\\1;npdi!",
      "prefix": "+22",
      "name": "+22 Numbers"
    }
  ]
}
```

This time (Trace2.sas), `extra-parameter-here` was added.

This isn't consistent with how bgcf.json works - that always matches on the most specific rule, ignoring order in the file. To make sure of this, my bgcf.json was set up as follows throughout:

```
{
    "routes" : [
       {    "name" : "adffbfdsfs",
            "number" : "+2",
            "route" : ["sip:nowhere"]
       },
       {    "name" : "e4re",
            "number" : "+22",
            "route" : ["sip:nowhere"]
       },
       {    "name" : "zzzzz",
            "number" : "+222",
            "route" : ["sip:nowhere"]
       },
       {    "name" : "adffbfdsfs",
            "number" : "+2223",
            "route" : ["sip:icscf.sprout.ame22.clearwater.test;transport=TCP"]
       },
       {    "name" : "off-net calling",
            "domain" : "*",
            "route" : ["sip:icscf.sprout.ame22.clearwater.test;transport=TCP"]
       }
    ]
}
```

#### Impact

It's not possible to lay out your enum.json file in the way that makes most sense (to me, at least) - starting with the most general rules first, then listing specific exceptions like ported numbers.

It's also possible to accidentally change routing behaviour, potentially causing an outage, by moving rules around.

Users also have to remember differences in how the superficially-similar bgcf.json and enum.json files work, making the product feel less polished overall.

#### Release and environment 

`10.0.0-20161116-~255.00.0-161116.175811`

#### Steps to reproduce

Create an enum.json with a shorter prefix listed before a longer prefix. Make a call to a number with the longer prefix.

**Comment by rkd-msw** [comment]
Traces at \\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1619

**Comment by rkd-msw** [comment]
Andrew - you said you'd be able to pick this up. (With this and the other two I've just passed over, it's worth checking with Ying/Adam whether these are in V11 or V10.)

**Comment by AME2** [comment]
I can confirm that we now match on the more specific prefix first.
