### ISSUE TITLE
Calls to +22233 and +5678;rn=+22233 are routed differently when the default route is used

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1621]
#### Symptoms

Intuitively, I'd expect `tel:+22233` and `tel:+5678;rn=+22233` to be routed the same way - that's the point of the routing number. However, the former can go down the default/wildcard route and the latter can't.

My config files were:

```

clearwater@ame21-sprout-1:~$ cat /etc/clearwater/enum.json
{
  "number_blocks": [
    {
      "regex": "!(^.*$)!tel:\\1;rn=+22233;npdi!",
      "prefix": "+5678",
      "name": "+5678 Numbers"
    },
    {
      "regex": "!(^.*$)!tel:\\1;npdi!",
      "prefix": "+22",
      "name": "+22 Numbers"
    }
  ]
}
clearwater@ame21-sprout-1:~$ cat /etc/clearwater/bgcf.json
{
    "routes" : [
       {    "name" : "off-net calling",
            "domain" : "*",
            "route" : ["sip:icscf.sprout.ame22.clearwater.test;transport=TCP"]
       }
    ]
}
```

Trace_22233.sas shows a call to +22233 which worked. Trace_5678.sas shows a call to +5678 which does get translated to use the routing number, but then fails with `404 No route to target`.

#### Impact

Ported numbers and non-ported numbers are routed differently. If users aren't aware of this, they may test the wrong thing after a routing change and cause an outage. Even if they are aware of it, it's one more thing to remember, and adds to the overall complexity of the product.

#### Release and environment 

`10.0.0-20161116-~255.00.0-161116.175811`

#### Steps to reproduce

Set up a bgcf.json file with only the default route. Make a call to a number which is translated by ENUM to a routing number.

**Comment by rkd-msw** [comment]
Upgrading to critical, as routing `tel:+22233` is a new feature.

**Comment by sebrexmetaswitch** [comment]
Just merged, so should be fixed in tomorrow's build

**Comment by rkd-msw** [comment]
Yes, fixed.
