### ISSUE TITLE
bgcf.json and enum.json are inconsistent in whether they allow visual separators in numbers

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1622]
#### Symptoms

Initially, I had my system configured like this:

```
clearwater@ame21-sprout-1:~$ cat /etc/clearwater/enum.json
{
  "number_blocks": [
    {
      "regex": "!(^.*$)!tel:\\1;npdi!",
      "prefix": "+22233",
      "name": "+22233 Numbers"
    }
  ]
}
clearwater@ame21-sprout-1:~$ cat /etc/clearwater/bgcf.json
{
    "routes" : [
       {    "name" : "off-net calling",
            "number" : "+2.2-2-(33)",
            "route" : ["sip:icscf.sprout.ame22.clearwater.test;transport=TCP;myparam"]
       }
    ]
}
```

The visual separators in bgcf.json (i.e. representing the number as `+2.2-2-(33)`) worked - see Working.sas.

Then I changed my enum.json to:

```
{
  "number_blocks": [
    {
      "regex": "!(^.*$)!tel:\\1;npdi!",
      "prefix": "+2.2-2-(33)",
      "name": "+22233 Numbers"
    }
  ]
}
```

i.e. with the "prefix" field in the same format as the "number" field in bgcf.json. In this case, I got the SAS log saying "ENUM processing for +22233 failed to find a terminal rule" - see ENUM_failed.sas. (By chance, the call happened to succeed because the ENUM failure meant it got sent to the BGCF, but it would have failed or been misrouted if I was relying on ENUM to change the number in some way.)

#### Impact

This is a minor inconsistency, but it will confuse the user and make the details of what each fie has to look like harder to remember.

Additionally, because the enum.json file is accepted rather than rejected with a parsing error (as it would be for invalid JSON), it's possible to make a mistake that causes a service outage for some subscribers (because their ENUM rule stops matching) and not notice.

#### Release and environment 

`10.0.0-20161116-~255.00.0-161116.175811`

#### Steps to reproduce

Configure an enum.json rule with (, ), - or . in the prefix. Attempt to make a call which should match that prefix.

**Comment by Ying-metaswitch** [comment]
Passing back for testing

**Comment by rkd-msw** [comment]
Andrew - you said you'd be able to pick this up.

**Comment by AME2** [comment]
I can confirm inbuilt ENUM now has the ability to match on a number containing visual separators
