### ISSUE TITLE
Sprout converts a 503 Service Unavailable from Homestead into a 404 Not Found

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1623]
#### Symptoms

In the SAS traces at \\ad\csd\bigfiles\clearwater\issue-attachments\homestead\268, Homestead returns a 503 Service Unavailable over HTTP. Sprout then sends a 404 Not Found over SIP.

#### Impact

5xx errors are server errors, whereas 4xx errors are client errors, so this is misleading - it encourages you to start looking in the wrong place (e.g. did the dialled subscriber not exist?). If announcements get played based on SIP status codes, this could also be confusing to the end user.

#### Release and environment 

`10.0.0-20161116-~255.00.0-161116.174523`

#### Steps to reproduce

I hit this while reproducing Homestead issue 268, but any call while the Cassandra database is down should reproduce this.

**Comment by rkd-msw** [comment]
Same kind of issue as https://github.com/Metaswitch/sprout/issues/1616.

**Comment by rkd-msw** [comment]
And in the same vein, a 504 on a UAR gets turned into a 480 Temporarily Unavailable by Sprout.

**Comment by sebrexmetaswitch** [comment]
Just merged a PR which fixes the 503->404 issue here: #1748 

This is also a workaround for: https://github.com/Metaswitch/homestead/issues/387 so passing back to you to re-test and confirm that we now send 504 errors instead.

(I'll raise another Sprout issue for the more general problem that we don't convert HTTP error codes to SIP in Sprout very well)

**Comment by rkd-msw** [comment]
Doesn't seem to have worked - see attachment. clearwater-version says:

```
clearwater@stress-sprout-1:~$ clearwater-version
astaire                        10.0.0-170302-~255.00.0-170302.020420
astaire-libs                   10.0.0-170302-~255.00.0-170302.020420
chronos                        10.0.0-170302-~255.00.0-170302.020420
clearwater-cluster-manager     10.0.0-170302-~255.00.0-170302.020420
clearwater-config-manager      10.0.0-170302-~255.00.0-170302.020420
clearwater-craft               10.0.0-170302-~255.00.0-170302.020420
clearwater-diags-monitor       10.0.0-170302-~255.00.0-170302.020420
clearwater-etcd                10.0.0-170302-~255.00.0-170302.020420
clearwater-infrastructure      10.0.0-170302-~255.00.0-170302.020420
clearwater-log-cleanup         10.0.0-170302-~255.00.0-170302.020420
clearwater-management-sdk      10.0.0-170302-~255.00.0-170302.020420
clearwater-memcached           10.0.0-170302-~255.00.0-170302.020420
clearwater-monit               10.0.0-170302-~255.00.0-170302.020420
clearwater-nginx               10.0.0-170302-~255.00.0-170302.020420
clearwater-queue-manager       10.0.0-170302-~255.00.0-170302.020420
clearwater-radius-auth         10.0.0-170302-~255.00.0-170302.020420
clearwater-snmp-alarm-agent    10.0.0-170302-~255.00.0-170302.020420
clearwater-snmpd               10.0.0-170302-~255.00.0-170302.020420
clearwater-snmp-handler-astaire 10.0.0-170302-~255.00.0-170302.020420
clearwater-socket-factory      10.0.0-170302-~255.00.0-170302.020420
clearwater-tcp-scalability     10.0.0-170302-~255.00.0-170302.020420
cwc-infrastructure             10.0.0-170302-~255.00.0-170302.020420
memcached-clearwater           1.6.00-0+10.0.0.170302.~255.00.0+0.5
metaswitch-core-sprout         10.0.0-170302-~255.00.0
sprout                         10.0.0-170302-~255.00.0-170302.020420
sprout-base                    10.0.0-170302-~255.00.0-170302.020420
sprout-bgcf                    10.0.0-170302-~255.00.0-170302.020420
sprout-icscf                   10.0.0-170302-~255.00.0-170302.020420
sprout-libs                    10.0.0-170302-~255.00.0-170302.020420
sprout-mmtel-as                10.0.0-170302-~255.00.0-170302.020420
sprout-node                    10.0.0-170302-~255.00.0-170302.020420
sprout-scscf                   10.0.0-170302-~255.00.0-170302.020420
```

**Comment by sebrexmetaswitch** [comment]
The 480 attachment is a very different flow - we get a timeout from the HSS, and Homestead returns a 504 to Sprout. This fix wasn't intended to cover that case.

The 404 is a bit more interesting - here, we're getting a 503 from Homestead. The difference here is that we're getting a 503 from the first homestead, and a plain timeout from the second. Sprout doesn't appear to be treating the timeout as a 503 response. I think this may be a simple case of not interpreting the curl timeout as a 503, which is probably a trivial fix. I'll take a look

**Comment by rkd-msw** [comment]
The 480 trace is an older attachment (I attached it with this comment -https://github.com/Metaswitch/sprout/issues/1623#issuecomment-265782712). The 404 trace is the one I uploaded yesterday.

**Comment by sebrexmetaswitch** [comment]
Ah, my bad, thanks for clearing that up.

**Comment by sebrexmetaswitch** [comment]
I've merged the fix to treat a timeout as a 503 error, which should fix the above case. As agreed, you're going to re-test on the next nightly build.

**Comment by rkd-msw** [comment]
OK, I don't see any 404 Not Found errors in my latest stress run - only 480 Temporarily Unavailable and 504 Server Timeout, both of which I think are reasonable.
