### ISSUE TITLE
Sprout is killed by monit at overload (180,000 subscribers)

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1626]
#### Symptoms

 I ran stress against a Sprout node, emulating 180,000 subscribers for 1 minute, starting at 18:37:59.

This is higher than rated load for Sprout, but I expected it to start rejecting traffic with 503 responses and degrade gracefully. Instead, Monit killed it:

```
[UTC Dec  1 18:38:20] error    : 'poll_sprout_sip' '/usr/share/clearwater/bin/poll_sprout_sip.sh' failed with exit status (1) -- SIP poll failed to 10.225.166.44:5054 with Call-ID poll-sip-278468 at 2016-12-01 18:38:10.148078347+00:00
stderr was:
Connection to 10.225.166.44 5054 port [tcp/*] succeeded!
stdout was:
[UTC Dec  1 18:38:30] error    : 'poll_sprout_sip' '/usr/share/clearwater/bin/poll_sprout_sip.sh' failed with exit status (1) -- SIP poll failed to 10.225.166.44:5054 with Call-ID poll-sip-278479 at 2016-12-01 18:38:20.240088549+00:00
stderr was:
Connection to 10.225.166.44 5054 port [tcp/*] succeeded!
stdout was:
[UTC Dec  1 18:38:30] info     : 'poll_sprout_sip' exec: /bin/bash
[UTC Dec  1 18:38:40] error    : 'poll_sprout_sip' '/usr/share/clearwater/bin/poll_sprout_sip.sh' failed with exit status (1) -- SIP poll failed to 10.225.166.44:5054 with Call-ID poll-sip-278489 at 2016-12-01 18:38:30.267169856+00:00
stderr was:
Connection to 10.225.166.44 5054 port [tcp/*] succeeded!
stdout was:
[UTC Dec  1 18:38:50] error    : 'sprout_process' process is not running
[UTC Dec  1 18:38:50] info     : 'sprout_process' trying to restart
[UTC Dec  1 18:38:50] info     : 'sprout_process' restart: /bin/bash
[UTC Dec  1 18:38:50] error    : 'poll_sprout_sip' '/usr/share/clearwater/bin/poll_sprout_sip.sh' failed with exit status (1) -- SIP poll failed to 10.225.166.44:5054 with Call-ID poll-sip-278499 at 2016-12-01 18:38:40.266064666+00:00
stderr was:
Connection to 10.225.166.44 5054 port [tcp/*] succeeded!
stdout was:
```

#### Impact

Call processing when overload is worse than expected, particularly due to high CPU/disk usage for diagnostics gathering.

#### Release and environment 

`1.0-cc-10.0.0-20161116-~255.00.0-161116.175811`

#### Steps to reproduce

Run `/usr/share/clearwater/bin/run_stress stress.clearwater.test 1800 3 --icscf-target 10.225.166.44:5052 --scscf-target 10.225.166.44:5054 --sipp-output --multiplier 100 --base-number 50132000 --ignore-initial-reg-failures`

**Comment by rkd-msw** [comment]
Diags bundle at \\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1626

**Comment by rkd-msw** [comment]
I've hit the same problem at 120k BHCA (which isn't overload, or shouldn't be) and uploaded a diags bundle.

**Comment by johadalin** [comment]
Investigated what was causing the poll script to fail. Looking at a pcap of the options polls, one can see that the failed poll (by call id) was sent a successful response, but that it took longer than a second. (The capture was on all traffic to port 5054 on the sprout node, then filtered in wireshark with `sip.Call-ID contains poll-sip`)

The poll-sip script currently has a wait_time parameter set to 1 second by default. This is the period that the netcat process will wait for a response to the poll message. 
I am not currently sure why it is taking longer than 1 second for sprout to respond to the poll when under load, without us seeing any throttling behaviour/503 responses. We should investigate further to make sure there is not an underlying issue.

Discussed with some of the team, and decided that the wait_time of 1 second is fairly short, as occasional increases in latency are acceptable, and we shouldn't just kill the process if it is overloaded. Suggested initial workaround/fix is to increase this value, probably to 2 (or maybe 3) seconds, and then to make sure that the overload behaviour is working as we expect.

**Comment by rkd-msw** [comment]
Increasing the wait time seems to have gone OK for 180,000 subscribers - I ran for 5 minutes without seeing issues - but that didn't actually trigger overload responses, and I wanted to make sure that at overload our load monitor did actually kick in and return 503 errors, rather than Monit just detecting slowness and killing Sprout.

So I increased the subscriber count to 250,000 and did hit this issue again after a few minutes, but didn't hit overload control. (I don't think I can get tcpdump at this load, because I don't have a way to filter only the monit polls and not the rest of the traffic - any suggestions?)

**Comment by johadalin** [comment]
Unclaiming for now, as other bugs are taking longer than expected, and given the other sprout bugs referenced, it may make sense for someone else to pick this up in the mean time. 
Will come back to this if not, as and when

**Comment by rkd-msw** [comment]
I think this is a combination of https://github.com/Metaswitch/sprout/issues/1728 and #1671:

* I'm using Mangelwurzel as an application server in these stress tests
* After sustained overload, it hits memory limits and dies
* This causes Sprout to die in turn, as it's Session-Terminated

I can't repro this issue under conditions not covered by https://github.com/Metaswitch/sprout/issues/1728 and #1671, so I'm closing it as a duplicate - but note that per #1671 and #1753 there are still issues at overload.
