### ISSUE TITLE
Misconfigured Sprout hostname in shared_config causes nonsense error

### ISSUE THREAD

**Issue by pdavies** [Metaswitch/sprout#1631]
#### Symptoms
I incorrectly added a port to my sprout hostname in shared_config, so I had a line reading:

> `sprout_hostname=sprout.host.name:8888`

Sprout fails to start, and reports the following error to `/var/log/sprout/sprout_current.txt`:

> `The sprout hostname (sprout.host.name:8888) can't be an IP address`

#### Impact
The error is confusing, and the cause (you can't add a port number) is not necessarily obvious, given that `hs_hostname` typically _does_ contain a port number.

#### Release and environment 
`10.0.0-20161205-~255.00.0`

#### Steps to reproduce
Add a port number to the `sprout_hostname` in shared_config, upload, and check `/var/log/sprout/sprout_current.txt`.

**Comment by eleanor-merry** [comment]
Should be fixed by the associated PR, passing back for retest

**Comment by pdavies** [comment]
Confirmed fixed.
