### ISSUE TITLE
REGISTER expires 0 gets 401 Unauthorized rather than deregistering

### ISSUE THREAD

**Issue by markrutter** [Metaswitch/sprout#1640]
#### Symptoms
Turning off WiFi calling on an iPhone 6s to deregister sent REGISTER Expires: 0. Sprout responds with 401 Unauthorized. There is no response to this from the iPhone and the public identity remains registered as seen e.g. on the HSS.

The REGISTER Expires: 0 was over IPSec with the same ports and contact information as the previous successful REGISTER so there is no need for authentication (it is equivalent to an INVITE in that respect).

The VoLTE Service Description and Implementation Guidelines Version 2.0 07 October 2014 shows example sequence in 3.2.2 VoLTE UE Initiated Detach and IMS Deregistration shows IMS deregistration without any further authentication - see here:
http://www.gsma.com/network2020/wp-content/uploads/2014/10/FCM.01-VoLTE-Service-Description-and-Implementation-Guidelines-Version-2.0.pdf

#### Impact
Minor. Prevents test of deregistering.

#### Release and environment 
Running on VMWare
clearwater@sprout-1:~$ clearwater-version
astaire                        9.0.0-1-1.0.0-160506.123137
astaire-libs                   9.0.0-1-1.0.0-160506.123137
chronos                        9.0.0-1-1.0.0-160506.123137
clearwater-cluster-manager     9.0.0-1-1.0.0-160506.123137
clearwater-config-manager      9.0.0-1-1.0.0-160506.123137
clearwater-diags-monitor       9.0.0-1-1.0.0-160506.123137
clearwater-etcd                9.0.0-1-1.0.0-160506.123137
clearwater-infrastructure      9.0.0-1-1.0.0-160506.123137
clearwater-log-cleanup         9.0.0-1-1.0.0-160506.123137
clearwater-memcached           9.0.0-1-1.0.0-160506.123137
clearwater-monit               9.0.0-1-1.0.0-160506.123137
clearwater-net-snmp            9.0.0-1-1.0.0-160506.123137
clearwater-queue-manager       9.0.0-1-1.0.0-160506.123137
clearwater-snmp-alarm-agent    9.0.0-1-1.0.0-160506.123137
clearwater-snmpd               9.0.0-1-1.0.0-160506.123137
clearwater-snmp-handler-astaire 9.0.0-1-1.0.0-160506.123137
clearwater-socket-factory      9.0.0-1-1.0.0-160506.123137
clearwater-tcp-scalability     9.0.0-1-1.0.0-160506.123137
cwc-infrastructure             9.0.0-1-1.0.0-160506.123137
memcached-clearwater           1.6.00-0+9.0.0.1.1.0.0+0.5
metaswitch-core-sprout         9.0.0-1-1.0.0
sprout                         9.0.0-1-1.0.0-160506.123137
sprout-base                    9.0.0-1-1.0.0-160506.123137
sprout-bgcf                    9.0.0-1-1.0.0-160506.123137
sprout-icscf                   9.0.0-1-1.0.0-160506.123137
sprout-libs                    9.0.0-1-1.0.0-160506.123137
sprout-mmtel-as                9.0.0-1-1.0.0-160506.123137
sprout-scscf                   9.0.0-1-1.0.0-160506.123137

#### Steps to reproduce
iPhone 6s using Voice over Wifi calling and registered
Turn off WiFi calling in Settings > Phone to deregister
Requires access to trace and/or HSS to check.

**Comment by markrutter** [comment]
\\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1640 includes SAS trace

**Comment by rkd-msw** [comment]
Looking at that trace, the P-CSCF has added `integrity-protected=no` to the REGISTER, which indicates that Sprout should challenge it. If you get the P-CSCF to add `integrity-protected=yes`, based on the fact this has come over an established IPSec connection, I'd expect this flow to work.

**Comment by markrutter** [comment]
That makes sense. Thanks.
