### ISSUE TITLE
Setting the Chronos hostname in shared config means that Sprout can't start

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/sprout#1656]
#### Symptoms
Setting chronos_hostname in shared_config means that Sprout fails to start with the following error:

```
20-12-2016 10:09:57.238 UTC Debug alarm.cpp:241: Started reraising alarms every 30 seconds
20-12-2016 10:09:57.238 UTC Debug alarm.cpp:253: Reraising all alarms with a known state
20-12-2016 10:09:57.255 UTC Verbose pjsip:          pjlib epoll I/O Queue created (0x7fb1594f34c0)
20-12-2016 10:09:57.255 UTC Verbose pjsip: sip_endpoint.c Module "mod-msg-print" registered
20-12-2016 10:09:57.255 UTC Debug pjsip: sip_transport. Transport manager created.
20-12-2016 10:09:57.255 UTC Verbose pjsip: sip_endpoint.c Module "mod-tsx-layer" registered
20-12-2016 10:09:57.255 UTC Verbose pjsip: sip_endpoint.c Module "mod-stateful-util" registered
20-12-2016 10:09:57.255 UTC Verbose pjsip: sip_endpoint.c Module "mod-sprout-util" registered
20-12-2016 10:09:57.255 UTC Error stack.cpp:325: Failed to start UDP transport for port 172 (Permission denied)
20-12-2016 10:09:57.255 UTC Error pjsip: Assert failed: stack.cpp:767 status == 0
20-12-2016 10:09:57.256 UTC Error main.cpp:1771: Error initializing stack Permission denied
```
 

#### Impact
Sprout can't start!

#### Release and environment 
From at least Sandslash

#### Steps to reproduce
Set chronos_hostname, attempt to start.

**Comment by eleanor-merry** [comment]
This is because of how we parse the chronos hostname from the config (https://github.com/Metaswitch/sprout/blob/dev/src/main.cpp#L1153). Importantly, we don't break once we've finished the case, so we fall into the listen_port case below. The listen port then parses the Chronos hostname as an int (which converted 172.*.*.* to 172).

**Comment by richardwhiuk** [comment]
Seen on StackOverflow under http://stackoverflow.com/questions/41012323/project-clearwater-sprout-not-working-after-update
