### ISSUE TITLE
Blocking a HSS's connection to one Homestead VM from a duplex pair causes registrations to fail for 30 seconds

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1658]
I was doing some resiliency testing using a deployment with two Sprouts, two Homesteads, one Ralf and one external HSS. Using iptables I had blocked the HSS's incoming connections from Homestead-1. I attempted to register a subscriber who had been provisioned against the external HSS. I expected to see the following flow:

- Homestead-1 sends diameter message to HSS
- Homestead-1 doesn't receive a response
- Homestead-1 tells a Sprout node that they are having trouble contacting the HSS
- Sprout asks Homestead-2 to contact the HSS
- Homestead-2 sends a diameter message to the HSS and receives a response.

#### Symptoms
The flow I actually saw was:
- Homestead-1 sends diameter message to HSS
- Homestead-1 doesn't receive a response
- Homestead-1 tells a Sprout node that they are having trouble contacting the HSS
- Sprout sends a 480 Temporarily Unavailable error message to Perimeta

This meant that the subscriber was unable to register. This happens more than 50% of the time, whenever Homestead-1 gets involved in the diameter flow subscribers cannot register.

[Homestead cant contact HSS.zip](https://github.com/Metaswitch/homestead/files/666742/Homestead.cant.contact.HSS.zip)

This does heal itself after around thirty seconds though with subscribers successfully registering. I've attached a SAS trace of the registration after the deployment has healed.

[Homestead can't contact HSS healing.zip](https://github.com/Metaswitch/sprout/files/668572/Homestead.can.t.contact.HSS.healing.zip)

It looks as though when Homestead discovers that it no longer has any diameter peers it will send a HTTP: 503 back to Sprout, which will cause Sprout to ask Homestead-2 to query the HSS. This is in contrast to the above case where Homestead thinks it still has a diameter connection and will send a HTTP: 504 back to Sprout, which causes Sprout to send a 480 to Perimeta. 

I included diags packages from both Sprout and Homestead in \\ad\csd\bigfiles\clearwater\issue-attachments\Sprout\1658

#### Impact
This could have quite a significant impact on the deployment. If network connectivity is ever lost between a Homestead node and a HSS then all of the deployment's subscribers would not be able to register.

#### Release and environment 
2 Sprouts: 10.0.0-161216-~255.00.0
2 Homesteads: 10.0.0-161216-~255.00.0
1 Ralf: 10.0.0-161216-~255.00.0
1 real external HSS

#### Steps to reproduce
Create a deployment as above. Log on to the HSS and use the following command to block incoming connections from a Homestead node:

`iptables -A INPUT -s <Homestead's IP address> -j DROP`

Try registering a subscriber. Note you may have to try a few times to get the registration to fail.

**Comment by sebrexmetaswitch** [comment]
The failures happen because we get a 504 response from homestead. The reason that sprout doesn't retry a different homestead on 504 response is that we can't distinguish this kind of timeout from one caused by an overloaded HSS, and we don't want to make the overload problem worse.

The deployment recovers, because after 30s homestead notices it has no active diameter connections and begins sending 503 responses instead, which do get retried to a different homestead.

We think the best fix here is to blacklist homestead on a 504 response, but still not retry. This means that the first call/registration will still fail, but that all others should succeed. Once it becomes greylisted (after 30s) homestead should notice that it has no diameter connections and begin returning 503 reponses, as it did here, so calls should work again.

**Comment by mirw** [comment]
Changing the 504 backlisting behavior is a possible solution here, but it has quite a broad impact.  I think we need to think this through carefully - are you OK to drive that, @sebrexmetaswitch?

**Comment by rkd-msw** [comment]
For the record, we've had one case in the field where we *didn't* get back into a good state after 30 seconds (although we didn't get a diags package so don't know why), which caused ongoing call failures, so I'm quite keen to do something better here.

**Comment by sebrexmetaswitch** [comment]
The change we've gone for here is that Homestead should now report an HTTP 503 error on a Diameter transaction timeout. This will then be retried to a new homestead by sprout.

Should be in tonight's nightly, so back to you to retest.

**Comment by AME2** [comment]
I've retested and can confirm this is fixed. Homestead does now report a HTTP 503 error which causes Sprout to retry.
[Fixed.zip](https://github.com/Metaswitch/sprout/files/729945/Fixed.zip)
