### ISSUE TITLE
Log spam leading to 3GB log file and maybe crashes: Error (Net-SNMP): Use snmp_sess_select_info2() for processing large file descriptors

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1662]
#### Symptoms

This log appears repeatedly:

```
03-01-2017 06:14:07.559 UTC Error (Net-SNMP): Use snmp_sess_select_info2() for processing large file descriptors
03-01-2017 06:14:07.559 UTC Error (Net-SNMP): Use snmp_sess_select_info2() for processing large file descriptors
03-01-2017 06:14:07.559 UTC Error (Net-SNMP): Use snmp_sess_select_info2() for processing large file descriptors
03-01-2017 06:14:07.559 UTC Error (Net-SNMP): Use snmp_sess_select_info2() for processing large file descriptors
03-01-2017 06:14:07.559 UTC Error (Net-SNMP): Use snmp_sess_select_info2() for processing large file descriptors
```

I see it about 40-70 times a millisecond:

```
11:40:19  sprout $ grep "06:14:07.559" sprout_20170103T060000Z.txt | grep snmp_sess_select_info2 | wc -l
48
11:41:36  sprout $ grep "06:14:07.560" sprout_20170103T060000Z.txt | grep snmp_sess_select_info2 | wc -l
69
```

#### Impact

My log file was 2.7 GB, making it difficult to diagnose other issues. (My Sprout process was also killed by Monit, although it's difficult to tell whether that is related.)

#### Release and environment 

10.0.0-161216-~255.00.0-161216.020317

This was a system that was both running stress (160,000 subscribers) and receiving SNMP polls at a low rate (one snmpwalk on each node every 5 minutes).

#### Steps to reproduce

Unknown, although running stress and SNMP polls would probably be a good bet. (Presumably this reproduces whenever Sprout has more than 1,024 file descriptors open?)

**Comment by rkd-msw** [comment]
Maybe related to the fix for https://github.com/Metaswitch/sprout/issues/1527?

**Comment by rkd-msw** [comment]
Diags package at `\\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1662`

**Comment by richardwhiuk** [comment]
I wonder whether this is related to https://github.com/Metaswitch/clearwater-net-snmp/pull/12 ?

**Comment by mirw** [comment]
I think I've fixed this under https://github.com/Metaswitch/clearwater-net-snmp/issues/13.  @rkd-msw, please can you let me know if you see this again?

**Comment by rkd-msw** [comment]
I'm no longer seeing this on 10.0.0-170118-~255.00.0-170118.020317 despite several stress runs:

```
clearwater@stress-sprout-1:~$ grep snmp_sess_select_info2 /var/log/sprout/*
clearwater@stress-sprout-1:~$
```

```
clearwater@stress-sprout-2:~$  grep snmp_sess_select_info2 /var/log/sprout/*
clearwater@stress-sprout-2:~$
```
