### ISSUE TITLE
Inconsistent behaviour on attempting to reuse a failed transport

### ISSUE THREAD

**Issue by GAB-MS** [Metaswitch/sprout#1679]
This is an issue I hit where a sproutlet was erroneously attempting to send a duplicate invite (with the same R-URI, and to the same non-existent destination, as the previously-sent invite). Sprout's behaviour in response to this is inconsistent - sometimes Sprout was acknowledging the transport error and sending an internal 503 to the responsible sproutlet, as with the first invite, which allows the sproutlet to perform further processing. However, sometimes Sprout was completely ignoring the transport error on the duplicate invite, which eventually resutls in the call timing out.

#### Symptoms

I've included relevant snippets of the logs below. The scenarios in both of the below cases are identical - in both cases, this is an attempt to send a SIP invite that is a duplicate of the prior invite (where the prior invite failed with a 503 generated by Sprout).

In this first case, a transport error is raised and a 503 is generated as expected.
```
11-01-2017 11:52:17.480 UTC Debug pjsip: tsx0x7fe53c037 Sending Request msg INVITE/cseq=2 (tdta0x7fe53c08c980) in state Null
11-01-2017 11:52:17.480 UTC Debug pjsip:       endpoint Request msg INVITE/cseq=2 (tdta0x7fe53c08c980): skipping target resolution because address is already set
11-01-2017 11:52:17.480 UTC Verbose common_sip_processing.cpp:136: TX 1716 bytes Request msg INVITE/cseq=2 (tdta0x7fe53c08c980) to TCP 203.0.113.0:5060:
--- SIP MESSAGE ---
11-01-2017 11:52:17.480 UTC Warning pjsip: tsx0x7fe53c037 Failed to send Request msg INVITE/cseq=2 (tdta0x7fe53c08c980)! err=120032 (Broken pipe)
11-01-2017 11:52:17.480 UTC Debug pjsip: tsx0x7fe53c037 State changed from Null to Terminated, event=TRANSPORT_ERROR
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:213: tsx0x7fe53c037f48 - tu_on_tsx_state UAC, TSX_STATE TRANSPORT_ERROR state=Terminated
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:1813: tsx0x7fe53c037f48 - uac_tsx = 0x7fe53c0158d0, uas_tsx = 0x7fe57403aaf0
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:1821: TRANSPORT_ERROR event on current UAC transaction
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:1841: Failed to connected to server so add to blacklist
11-01-2017 11:52:17.480 UTC Debug baseresolver.cpp:400: Add 203.0.113.0:5060 transport 6 to blacklist for 30 seconds, graylist for 0 seconds
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:1914: tsx0x7fe53c037f48 - UAC tsx terminated while still connected to UAS tsx
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:1917: Timeout or transport error
11-01-2017 11:52:17.480 UTC Debug basicproxy.cpp:1408: Dissociate UAC transaction 0x7fe53c0158d0 for target 2
11-01-2017 11:52:17.480 UTC Verbose sproutletproxy.cpp:684: Notifying upstream sproutlet  of client failure: TRANSPORT_ERROR
11-01-2017 11:52:17.480 UTC Verbose sproutletproxy.cpp:1683: -0x7fe57405d2e0 received error TRANSPORT_ERROR on fork 2, state = Calling
```

In this second case, a TCP send error occurs instead, with no further messages generated by Sprout. (The next trace after the end of this snippet is logged 22 seconds later, when the call times out.)
```
11-01-2017 11:52:26.187 UTC Debug pjsip: tsx0x7fe53c037 Sending Request msg INVITE/cseq=2 (tdta0x7fe53c08c980) in state Null
11-01-2017 11:52:26.187 UTC Debug pjsip:       endpoint Request msg INVITE/cseq=2 (tdta0x7fe53c08c980): skipping target resolution because address is already set
11-01-2017 11:52:26.187 UTC Verbose common_sip_processing.cpp:136: TX 1717 bytes Request msg INVITE/cseq=2 (tdta0x7fe53c08c980) to TCP 203.0.113.0:5060:
--- SIP MESSAGE ---
11-01-2017 11:52:26.187 UTC Debug pjsip: tsx0x7fe53c037 State changed from Null to Calling, event=TX_MSG
11-01-2017 11:52:26.187 UTC Debug basicproxy.cpp:213: tsx0x7fe53c037f48 - tu_on_tsx_state UAC, TSX_STATE TX_MSG state=Calling
11-01-2017 11:52:26.187 UTC Debug basicproxy.cpp:1813: tsx0x7fe53c037f48 - uac_tsx = 0x7fe53c05f090, uas_tsx = 0x7fe544044570
11-01-2017 11:52:26.187 UTC Debug basicproxy.cpp:1821: TX_MSG event on current UAC transaction
11-01-2017 11:52:26.187 UTC Debug basicproxy.cpp:2134: Starting timer C
11-01-2017 11:52:26.187 UTC Debug pjsip: tcpc0x7fe5640a TCP send() error, sent=-70009
11-01-2017 11:52:26.188 UTC Debug pjsip: tsx0x7fe564027 Timeout timer event
11-01-2017 11:52:26.188 UTC Debug pjsip: tsx0x7fe564027 State changed from Terminated to Destroyed, event=TIMER
11-01-2017 11:52:26.188 UTC Debug basicproxy.cpp:213: tsx0x7fe564027858 - tu_on_tsx_state UAC, TSX_STATE TIMER state=Destroyed
11-01-2017 11:52:26.188 UTC Debug basicproxy.cpp:1813: tsx0x7fe564027858 - uac_tsx = 0x7fe5640204a0, uas_tsx = (nil)
11-01-2017 11:52:26.188 UTC Debug basicproxy.cpp:1985: tsx0x7fe564027858 - UAC tsx destroyed
11-01-2017 11:52:26.188 UTC Debug basicproxy.cpp:1535: BasicProxy::UACTsx destructor (0x7fe5640204a0)
11-01-2017 11:52:26.188 UTC Debug pjsip: tdta0x7fe56400 Destroying txdata Request msg INVITE/cseq=2 (tdta0x7fe5640009f0)
```

Full diags are in the usual place.

#### Impact
This is an unlikely scenario, as it requires a duplicate SIP invite to be sent out (which is already erroneous in itself), but Sprout's behaviour should be consistent. The current behaviour can potentially impact testing, and can make the erroneous behaviour less clear.

#### Release and environment 
Using the latest Sprout dev code, on an AWS node spun up using Chef, in a full Project Clearwater deployment.

**Comment by huws** [comment]
This issue isn't quite as unlikely as the text above makes it sound.  This issue affects any case where pjsip hits a TCP transport error, and then the sproutlet tries to send an additional request to the same address/port.  The contents of the SIP messages are unimportant, and this applies whether we're sending duplicate INVITEs or very different INVITEs that happen to share the same next hop (e.g. failover between routes by a BGCF, both of which go via the local IBCF).

More details in https://github.com/Metaswitch/pjsip-upstream/pull/57

**Comment by huws** [comment]
This is now fixed in `release-114-fixes` and `master`.  

@GAB-MS - I'm closing this issue, I'll use https://github.com/Metaswitch/houdini/issues/281 to cover the retest.
