### ISSUE TITLE
Sprout process is killed by monit when the VM boots up

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1684]
#### Symptoms

* I rebooted my Sprout node, and it came back up at 11:44:21
* The Sprout process started at 11:44:57
* I got a "Fatal - The application has exited or crashed with signal Aborted." log at 11:46:03
* The Sprout process started again at 11:46:06
* I got another "Fatal - The application has exited or crashed with signal Aborted." log at 11:46:32
* The Sprout process started again at 11:46:39
* I got another "Fatal - The application has exited or crashed with signal Aborted." log at 11:47:03
* The Sprout process started again at 11:47:09

It seems to have been running OK since then.

#### Impact

Normal startup results in the following worrying ENT log:

```
2004 - Description: Fatal - The application has exited or crashed with signal Aborted. @@Cause: The application has encountered a fatal software error or has been terminated. @@Effect: The application will exit and restart until the problem is fixed. @@Action: Ensure that the node has been installed correctly and that it has valid configuration.
```

#### Release and environment 

`10.0.0-170112-~255.00.0-170112.020313`

#### Steps to reproduce

Boot or reboot a Sprout VM. Check /var/log/syslog.

**Comment by rkd-msw** [comment]
Diags at `\\ad\csd\bigfiles\clearwater\issue-attachments\sprout\1684`, with syslog and monit.log already extracted from the tar file.

**Comment by sebrexmetaswitch** [comment]
It looks like sprout was being restarted because the poll_sprout_http process decided it wasn't running:

> 'poll_sprout_http' '/usr/share/clearwater/bin/poll_sprout_http.sh' failed with exit status (1) -- HTTP failed to http://10.225.166.96:9888/ping

I've just fixed a bug in #1704 which resulted in the http stack not listening on its socket correctly. In that case, it was the management API stack, but the bug affects both management and signalling. I think that bug caused this - if sprout's signalling http stack isn't listening correctly, the http poll script will continuously fail and sprout will get restarted. Eventually it settles down because it's a race condition (try enough times and we time it right.)

That fix will be in the next nightly, so back to you to re-test.

**Comment by rkd-msw** [comment]
Looks good - just the two expected restarts (on first boot and when shared_config is propagated):

```
clearwater@gr-stress-site1-sprout-1:~$ grep sprout_process /var/log/monit.log
[UTC Feb  9 03:56:30] error    : 'sprout_process' process is not running
[UTC Feb  9 03:56:30] info     : 'sprout_process' trying to restart
[UTC Feb  9 03:56:30] info     : 'sprout_process' restart: /bin/bash
[UTC Feb  9 03:56:54] error    : 'sprout_process' failed to restart (exit status 127) -- /bin/bash: zmq_msg_recv: Resource temporarily unavailable
[UTC Feb  9 03:57:42] error    : 'sprout_process' process is not running
[UTC Feb  9 03:57:42] info     : 'sprout_process' trying to restart
[UTC Feb  9 03:57:43] info     : 'sprout_process' restart: /bin/bash
[UTC Feb  9 03:58:13] error    : 'sprout_process' failed to restart (exit status 0) -- /bin/bash:  * Restarting Sprout SIP Router sprout
[UTC Feb  9 04:05:15] error    : 'sprout_process' process is not running
[UTC Feb  9 04:05:15] info     : 'sprout_process' trying to restart
[UTC Feb  9 04:05:34] info     : 'sprout_process' restart: /bin/bash
[UTC Feb  9 04:06:04] error    : 'sprout_process' failed to restart (exit status -1) -- /bin/bash: Program timed out --  * Restarting Sprout SIP Router sprout
[UTC Feb  9 04:08:16] error    : 'sprout_process' process is not running
[UTC Feb  9 04:08:16] info     : 'sprout_process' trying to restart
[UTC Feb  9 04:08:49] info     : 'sprout_process' restart: /bin/bash
[UTC Feb 10 16:20:32] error    : 'sprout_process' process is not running
[UTC Feb 10 16:20:32] info     : 'sprout_process' trying to restart
[UTC Feb 10 16:20:32] info     : 'sprout_process' restart: /bin/bash
[UTC Feb 10 16:24:34] error    : 'sprout_process' process is not running
[UTC Feb 10 16:24:34] info     : 'sprout_process' trying to restart
[UTC Feb 10 16:24:34] info     : 'sprout_process' restart: /bin/bash
[UTC Feb 10 16:24:45] info     : 'sprout_process' process is running with pid 5034
```

**Comment by rkd-msw** [comment]
(Ignoring the 4am ones as they come from the build process)
