### ISSUE TITLE
Sprout doesn't respond to management HTTP requests

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1713]
#### Symptoms

I have 2 Sprout nodes, 10.225.166.42 and 10.225.166.43. 43 is responding to management HTTP requests (e.g. for the `/impu/sip:5012801378@stress.clearwater.test/bindings` URL), but 42 isn't. Instead, nginx returns a 504 Gateway Timeout after 60 seconds.

The two nodes are on the same software version (10.0.0-170131-~255.00.0-170131.020417)

I've attached packet capture showing the requests and a diags package from the failed node.

#### Impact

Can't display information about subscriber bindings, or deregister a subscriber.

#### Release and environment 

10.0.0-170131-~255.00.0-170131.020417

#### Steps to reproduce

Unknown - but I'd applied a patch upgrade to these systems earlier, so that may have caused it (e.g. by deleting something from under nginx's feet)

**Comment by chris-elford-metaswitch** [comment]
I'd like to understand when this happens before deciding that it's not critical.

**Comment by sebrexmetaswitch** [comment]
The error's we're getting from nginx are like:

> 2017/01/31 13:29:19 [error] 15509#0: *286 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ::ffff:10.225.166.42, server: sprout-mgmt.stress.clearwater.test, request: "GET /impu/sip:5012801378@stress.clearwater.test/bindings HTTP/1.1", upstream: "http://unix:/tmp/sprout-http-mgmt-socket/impu/sip:5012801378@stress.clearwater.test/bindings", host: "10.225.166.42:9886"

One thing that looks a bit suspicious is that there's no second ":" to mark the end of the unix socket. Contrast that with the following (on my test box, after stopping the sprout process):

> 2017/02/01 15:46:00 [error] 14863#0: *1255 connect() to unix:/tmp/sprout-http-mgmt-socket failed (111: Connection refused) while connecting to upstream, client: ::ffff:10.0.202.43, server: sprout.sr2.cw-ngv.com, request: "GET /impu/sip:3055550009@sr2.cw-ngv.com/bindings HTTP/1.1", upstream: "http://unix:/tmp/sprout-http-mgmt-socket:/impu/sip:3055550009@sr2.cw-ngv.com/bindings", host: "sprout.sr2.cw-ngv.com:9886"

I'm not sure what would have caused this difference, however.

**Comment by sebrexmetaswitch** [comment]
On some further investigation, I've also found that on the broken node, we see:

>sudo netstat --all --program | grep "sprout-http-mgmt-socket"

|  |   |      |      |            |     |     |    |
| --- | --- | --- | --- | --- | --- | --- | --- |
|Proto | RefCnt | Flags    |  Type   |    State       |  I-Node |  PID/Program name  |  Path |
|unix   | 2   |   [ ]   |      STREAM |    CONNECTING  |  0   |     -        |           /tmp/sprout-http-mgmt-socket |

vs on the working node:

>sudo netstat --all --program | grep "sprout-http-mgmt-socket"

|  |   |      |      |            |     |     |    |
| --- | --- | --- | --- | --- | --- | --- | --- |
|Proto | RefCnt | Flags    |  Type   |    State       |  I-Node |  PID/Program name  |  Path |
| unix | 3  |    [ ]  |       STREAM  |   CONNECTED  |   3119982 | 8638/sprout   |      /tmp/sprout-http-mgmt-socket |

**Comment by sebrexmetaswitch** [comment]
I've now merged a fix for this, so back to you to re-test. Should be in the next nightly build.

**Comment by rkd-msw** [comment]
I didn't have a clear repro scenario for this, so I'm just going to close.
