### ISSUE TITLE
Network failures don't get counted under the sproutInitialRegistrationFailures statistic

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1718]
I've been doing some testing of the [new KPIs](https://metacom.metaswitch.com/docs/DOC-105311) which v10 Clearwater Core nodes expose.

I have been testing the _Initial registration success of S-CSCF_ KPI which is exposed via the PROJECT_CLEARWATER_MIB in the sproutInitialRegistrationTable. 

Note that the design for this KPI makes it clear that this KPI should not track those registrations which have failed due to an **authentication error**, this would include trying to register a subscriber with the incorrect password.

To test the value of this KPI in a deployment with a network error I turned off all the homestead processes on my deployment. As expected registrations stopped working with Sprout sending out 403 forbidden (see trace)
[no_reg_failures_when_homestead_down.zip](https://github.com/Metaswitch/sprout/files/747848/no_reg_failures_when_homestead_down.zip)
 and I was expecting that sproutInitialRegistrationFailures would be incremented (seeing as in my opinion this is not an authentication error but rather a network error).

#### Symptoms
What actually happened was that the value of this KPI did not change.

#### Impact
This may prevent a network operator who is just monitoring the KPIs to not notice a network failure. Note an alarm should be raised so they should be alerted to the failure if they are monitoring alarms (which is why this issue is not critical).

#### Release and environment 
CC-homestead-10.0.0-170131-~255.00.0.ova
CC-ralf-10.0.0-170131-~255.00.0.ova
CC-sprout-10.0.0-170131-~255.00.0.ova

#### Steps to reproduce
Create a working Clearwater Core deployment. Make some registrations and use a MIB browser loaded with the PROJECT-CLEARWATER-MIB to query a Sprout node for the result of sproutInitialRegistrationEntry, you should see both Attempts and Successes have been incremented. Then stop the homestead processes on all Homestead nodes, attempt registrations and query the same statistic again.

**Comment by MatMeredith** [comment]
@AME2 Are there related issues here with the sproutICSCFSessionEstablishmentNetworkTable and sproutICSCFSessionEstablishmentTable stats?

**Comment by AME2** [comment]
@rkd-msw Can you please have a look at the above during your KPI testing?

**Comment by rkd-msw** [comment]
@MatMeredith - no, I don't think so. I think the issue here is that these are authentication-related failures from the point of view of the code (i.e. the Homestead queries are happening in authentication.cpp) but not from the point of view of the user.

sproutICSCFSessionEstablishmentNetworkTable and sproutICSCFSessionEstablishmentTable stats can't be misclassified as authentication in the same way, I think.

**Comment by rkd-msw** [comment]
@MatMeredith - also on those I-CSCF stats, this is a REGISTER, and the description of that stat is clear that it's only for INVITEs (and that matches my testing):

```
"Stats regarding attempts to establish terminating sessions at
                 the I-CSCF.  This provides stats about the same set of events
                 as the sproutICSCFSessionEstablishmentTable, but this time
                 only considering whether the request was successful from a
                 network perspective.
                 Each INVITE received by the I-CSCF (from the originating
                 S-CSCF) is counted as a terminating session attempt.
                 Such an attempt is considered successful from a network
                 perspective if either
                 - the I-CSCF responds with a 180 RINGING or 200 OK
                 - the session is canceled by the originating party before
                   being established
                 - the session is rejected with 486 BUSY HERE, 600 BUSY
                   EVERYWHERE, 404 NOT FOUND or 484 ADDRESS INCOMPLETE."
```

**Comment by MatMeredith** [comment]
Good point.   And on the initial issue here, the reason that the failures aren't tracked in the InitialRegistration stat is that this is an SCSCF stat and killing Homestead causes the requests to fail at the ICSCF...  @AME2 I think that means that a) this isn't a bug and can be closed, b) your test case hasn't actually tested the behaviour you were trying to test here, so you might want to retest?
