### ISSUE TITLE
A network experiencing packet loss can have failed calls which don't get tracked under the sproutICSCFSessionEstablishmentTable

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1719]
I've been doing some testing of the [new KPIs](https://metacom.metaswitch.com/docs/DOC-105311) which v10 Clearwater Core nodes expose.

I have been testing the _Session Establishment Success Rate_ and _Session Establishment Network Success Rate_ KPIs which are exposed via the PROJECT_CLEARWATER_MIB in the sproutICSCFSessionEstablishmentTable and the sproutICSCFSessionEstablishmentNetworkTable respectively.

To test these I introduced 10% packet loss on all traffic leaving all Sprout nodes in my deployment. To achieve this I used the command:

`/usr/share/clearwater/bin/run-in-signaling-namespace tcset --device eth1 --loss 10`

 I expected any call failures that arose as a result of the packet loss to be tracked as failures under both KPIs

#### Symptoms
Actually the number of failures both KPIs reported were 0.

You can see in the attached SAS trace that Sprout sent a 404: no route to target error:

[404_no_session_stat.zip](https://github.com/Metaswitch/sprout/files/748474/404_no_session_stat.zip)

A quicker way to cause Sprout to send a 404 is to turn all homestead processes off and attempt to make a call, I did this and the KPIs still did not report any failures:

[404_clients_no_session_stat.zip](https://github.com/Metaswitch/sprout/files/748479/404_clients_no_session_stat.zip)

#### Impact
This could prevent a network operator whose network is experiencing packet loss from ever realising that calls were failing. I consider this bug to be critical because in the case where a network is experiencing packet loss there are no alarms or other bits of diagnostics that could potentially warn an operator of the problem, this KPI is the only indication that they have that calls which have been failing.

#### Release and environment 
CC-homestead-10.0.0-170131-~255.00.0.ova
CC-ralf-10.0.0-170131-~255.00.0.ova
CC-sprout-10.0.0-170131-~255.00.0.ova

#### Steps to reproduce
Create a working Clearwater Core deployment. Make some calls and use a MIB browser loaded with the PROJECT-CLEARWATER-MIB to query a Sprout node for the result of sproutICSCFSessionEstablishmentEntry, you should see both Attempts and Successes have been incremented. Then stop the homestead processes on all Homestead nodes, attempt a call and query the same statistic again.

**Comment by AME2** [comment]
I've seen this again with 50% packet loss applied to all traffic leaving Sprout nodes. In this case Sprout sent a 480: Temporarily Unavailable after failing to contact Homestead. The KPI tracking failed registrations was still at 0.
[no_reg_failures_packet_loss.zip](https://github.com/Metaswitch/sprout/files/750395/no_reg_failures_packet_loss.zip)

**Comment by rkd-msw** [comment]
Looking at this, I think this is working as designed.

* sproutICSCFSessionEstablishmentEntry only counts terminating calls, i.e. on-net calls which get through originating S-CSCF processing and get to the I-CSCF or calls from off-net which come in directly to the I-CSCF
* these calls are failing on the originating side, so it's correct that they're not counted in the statistic

I think there's a separate stat at the P-CSCF for tracking the originating call success rate - @chris-elford-metaswitch , does that match your understanding? If so, this behaviour is expected.

**Comment by chris-elford-metaswitch** [comment]
Thanks Rob, good spot. This looks WAD to me too.

**Comment by rkd-msw** [comment]
(I have verified that this stat is not 100% when we have packet loss - some calls do get through originating processing and fail at terminating processing. That's about 1%.)
