### ISSUE TITLE
Sprout can send a 504 Server Timeout too early if it doesn't receive a response to a REGISTER

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1732]
I've been testing the process for upgrading Clearwater V9 -> V10.

As part of this process you scale your deployment out by adding extra V10 Sprout nodes to your deployment. As I was scaling out my deployment I hit a registration failure.

Note the case described where I see this failure is exactly the same as if you were attempting a register when one of your Sprout nodes have gone down, so this issue extends beyond just upgrades.

#### Symptoms
You can see the following flow in the attached SAS trace:

14:03:08.666: REGISTER flow begins
The REGISTER goes to Sprout-1 which successfully gets Homestead to do a UAR/UAA exchange with the HSS which causes Sprout-1 to receive a HTTP: 200 from Homestead.
14:03:08.676: Sprout-1 forwards the REGISTER message to the new Sprout node which at this time is in the process of being created and hence doesn't respond (this would be the same as having a Sprout node which is down)
14:03:08.677: Sprout-1 correctly starts recovering from this by forwarding the REGISTER on to a different Sprout node, Sprout-2. Sprout-2 successfully gets Homestead to do a MAR/MAA exchange which correctly causes a 401 to be send back to Sprout-1.
However at 14:03:08.677, before Sprout-1 receives the SIP: 401 Unauthorized from Sprout-2 (at 14:03:08.687), Sprout-1 sends a SIP: 504 Server Timeout back to Perimeta which causes the registration to fail.

You can see in the detailed timeline that at 14:03:08.677 Sprout-1 claims that "Selecting an S-CSCF failed", even though at this point Sprout-2 is behaving correctly and is about to get the SIP: 401 back to Sprout-1.

Sprout-1 needs to be more patient and wait a reasonable amount of time before sending the SIP: 504 Server Timeout. 

[Sprout issue.zip](https://github.com/Metaswitch/sprout/files/766981/Sprout.issue.zip)

#### Impact
This could cause call failure in the case where you are either upgrading your nodes or when one of your Sprout nodes has gone down but receives a REGISTER request.

#### Release and environment 
At this point during the upgrade I was running:

CC-ralf-10.0.0-170209-~255.00.0.ova
CC-homestead-10.0.0-170209-~255.00.0.ova

Sprout-1 and Sprout-2 were running:

CC-sprout-9.0.0-1-1.0.0.ova

The new Sprout node that I added to the deployment but was not responding was:

CC-sprout-10.0.0-170209-~255.00.0.ova

#### Steps to reproduce
Create a deployment with three Sprout nodes. Power off one of the Sprout nodes and attempt to make a registration.

**Comment by chris-elford-metaswitch** [comment]
At the moment, I don't understand whether this was a one-off window condition, or a more worrying systemic problem.

Let's figure out what the problem is, then decide how urgent it is to fix.

**Comment by AME2** [comment]
@chris-elford-metaswitch I will do some more testing today of whether we see the same issue when a Sprout node goes down during registration and get back to you.

**Comment by AME2** [comment]
@chris-elford-metaswitch I've done some testing to try and reproduce this in the most basic case: 3 Sprout nodes, one of which gets powered off, attempt a registration. I've not been able to reproduce the issue, which suggests it is a one-off window condition possibly related to the upgrade process. I'll drop this to high priority for now.

**Comment by rkd-msw** [comment]
If so, I suggest we close this. @johadalin - should https://github.com/Metaswitch/sprout/pull/1688 be back-applied?

**Comment by AME2** [comment]
@rkd-msw Yes it could be a V9 issue. The symptoms of this issue do appear to be the same as #1607 and I haven't been able to reproduce the problem on V10 nodes.

**Comment by johadalin** [comment]
I think i'd agree we could close this if that is the case. I am a bit concerned that we hit this though.
As i understand it, in a proper upgrade process, you should remove the sprout node from all DNS prior to removing it from clusters, and turning it down, and so even under the simplest condition of scaling down a v9 cluster by one node, we should never hit #1607 .
If that is a correct assumption, why did we hit the issue in this case? It's possible it's just DNS caching or something, but i'd like to understand that. 

If there is some step in the upgrade process that is causing us to enter a scenario where #1607 is a possibility, we need to clarify that, and then either work out a change to the upgrade process, or back apply #1688 so that we no longer drop any registers. 

If there is not a step in the process causing this, and it was just an off-chance thing we hit, then i'm fine to close this. We may still want to suggest back-applying the fix, but that would be something to pass up to L3.

**Comment by AME2** [comment]
@johadalin Yes you're correct that we shouldn't hit this during the upgrade process- I was concerned that would could hit this issue on a standard V10 deployment when one Sprout node goes down but it appears that isn't the case.

The issue was indeed with DNS, the script I was using to scale out the deployment (incorrectly) updated the DNS cluster record before adding the Sprout node to the cluster, this meant that from the DNS server's point of view we had an extra alive Sprout node that was in fact still in the process of spinning up.

**Comment by AME2** [comment]
Closing this as we should not hit this issue during a normal upgrade procedure following the docs.
