### ISSUE TITLE
Sprout is not running

### ISSUE THREAD

**Issue by Ahmedeldeeb91** [Metaswitch/sprout#1782]
After installing the sprout node following manual installation instructions here http://clearwater.readthedocs.io/en/stable/Manual_Install.html 
the sprout node process is not running 
after accessing log file i found at sprout_current,txt that there is an error
No local site registration store specified
so what is the problem

[sprout_current.txt](https://github.com/Metaswitch/sprout/files/837619/sprout_current.txt)
[monit_status.txt](https://github.com/Metaswitch/sprout/files/837621/monit_status.txt)

**Comment by sebrexmetaswitch** [comment]
Our manual install instructions were updated along with the last release at the end of last week.

As per the instructions here: http://clearwater.readthedocs.io/en/stable/Manual_Install.html#provide-shared-configuration, does your `/etc/clearwater/shared_config` contain

`sprout_registration_store=sprout.<zone>`

?

If not, you should add that to `shared_config` and then run `cw-upload_shared_config`

**Comment by eleanor-merry** [comment]
Closing as answered.
