### ISSUE TITLE
Retransmitted SIP requests do not appear in SAS. 

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#353]
The responses do however. 

This is because retranmissions are swallowed by the transaction module, whereas Call-ID correlation is done in the registrar/proxy/authentication modules (which are not invoked). Solution will be to correlate to the existing transaction in the stack module, and log the retransmission on the same trail as the original request.

**Comment by rkd-msw** [comment]
I've now seen this working.
