### ISSUE TITLE
sprout chokes on P-Served-User header with trailing semicolon

### ISSUE THREAD

**Issue by emcee21** [Metaswitch/sprout#373]
Reproduce: send INVITE to sprout with a P-Served-User header with a trailing semicolon inside the brackets, e.g.
Alice Wonderland &lt;sip:alice@example.com;foo=bar;this=that;&gt;;bling=bling

Expected: semicolon has no effect
Actual: No response from sprout is received.  Removing the semicolon results in normal processing of the INVITE, e.g.
Alice Wonderland &lt;sip:alice@example.com;foo=bar;this=that&gt;;bling=bling

**Comment by rkd-msw** [comment]
This should now be fixed, though I'll add a live test to explicitly confirm that.
