### ISSUE TITLE
Need to check for crash when shutting Sprout down with transactions in progress

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#427]
In UT, we hit an issue where the PJSIP transaction layer was shut down after modules such as the registrar module (i.e. after the registrar module's ID had been reset to -1), triggering memory issues when the transaction state callback tried to access mod_data[-1]. We fixed this in UT by advancing the time by 33s to end the transaction naturally, but should test this sort of shutdown live and verify that it's fine.

**Comment by eleanor-merry** [comment]
Closing as this is covered by #453
