### ISSUE TITLE
P-Charging-Vector icid-value parameters are rejected unnecessarily

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#486]
If bono needs to build a P-Charging-Vector, it uses the Call-ID as an icid-value.  (P-CSCFs are free to choose their own identifier, as long as it has the correct lifecycle.)

Jitsi generates a Call-ID including colons (maybe a hypothetical IPv6 address), and bono puts this on the P-Charging-Vector.

    P-Charging-Vector: icid-value=a2bb639b437cd5827a8f54fe39f3987c0:0:0:0:0:0:0:0;icid-generated-at=ec2-54-237-198-247.compute-1.amazonaws.com

sprout fails to parse this - it expects icid-value to be a normal parameter when actually it's defined to be a `gen-value`.  sprout should parse this.

**Comment by rkd-msw** [comment]
Fixed by #961.
