### ISSUE TITLE
sprout snmp OIDs .1.2.826.0.1.1578918.9.3.3.1 and .1.2.826.0.1.1578918.9.3.2.2 return no such instance exists at this OID

### ISSUE THREAD

**Issue by tcaterisano** [Metaswitch/sprout#540]
Is there a new MIB or have these OIDs been removed?

[sprout]ubuntu@sprout-1:~$ snmpwalk -v2c -c clearwater localhost  .1.2.826.0.1.1578918.9.3.2.2
iso.2.826.0.1.1578918.9.3.2.2 = No Such Instance currently exists at this OID
[sprout]ubuntu@sprout-1:~$ snmpwalk -v2c -c clearwater localhost  .1.2.826.0.1.1578918.9.3.3.1
iso.2.826.0.1.1578918.9.3.3.1 = No Such Instance currently exists at this OID

PROJECT-CLEARWATER::sprout.xdm.sproutXDMLatencyTable (.1.2.826.0.1.1578918.9.3.2.2)
PROJECT-CLEARWATER::sprout.hss.sproutConnectedHomesteadsTable (.1.2.826.0.1.1578918.9.3.3.1)

**Comment by rkd-msw** [comment]
https://github.com/Metaswitch/sprout/pull/1115 reworked SNMP handling in Sprout substantially, so I think this will be gone. (I've tested to confirm.)

Note that `sproutConnectedHomesteadsTable` deliberately won't report anything at start-of-day - we connect to Homesteads lazily, so until we've processed a REGISTER there are no connections to Homestead (and therefore no rows in that table).
