### ISSUE TITLE
sprout/memcached get into state where all requests fail

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#548]
Somehow, my system got into a state where all (or at least virtually all) requests to memcached fail.

From a code perspective, what would happen is that libmemcached/io.cc:418's call to `::recv` would always return 0.  0 indicates that the connection has already been closed by the far end.

I recovered the system by stop/restarting sprout.

My suspicion is that memcached was closing connections to keep the total number down and the usage pattern on sprout was such that each connection was created then put to one side (during which time memcached closed it) - then, when sprout did finally decide to use it, it could send but would fail to read immediately.

I suspect the fix is to change the sprout/libmemcached usage pattern - maybe creating TCP connections in advance isn't such a good idea?  Alternatively, we could look into what would cause memcached to close connections itself.

**Comment by bossmc** [comment]
Not seen for over a year (and we've tweaked out libmemcached usage in that time.  Closing.
