### ISSUE TITLE
No SAS correlation between Clearwater and CFS TAS for 3rd party registrations. 

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#575]
After registering a client with Clearwater and an associated CFS TAS, SAS shows two independent call flows for the registration. One shows up almost immediately from the CFS which shows its' interaction with an inferred (dashed line) Sprout. The second shows up a couple minutes later showing Perimeta and all Clearwater NEs with an inferred CFS TAS. These two flows should be merged into one, similar to a normal call flow.

**Comment by bossmc** [comment]
Raising to high as this sounds useful.

**Comment by rkd-msw** [comment]
Confirmed fixed.
