### ISSUE TITLE
sprout crashes should dump out SAS trail ID (if known)

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#587]
If sprout dumped out the SAS trail ID, this would make debugging stress problems much easier, as we could pull the SAS trial and so see what was going on at the time.

Marking as high-priority as this feels really useful.

**Comment by bossmc** [comment]
@mirw - What's the latest on this?

**Comment by mirw** [comment]
We can probably close this.  It would be nice to move SAS trail into the thread context, but it's not crucial.
