### ISSUE TITLE
SAS logging for reading bindings from the reg store is misleading

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#666]
SAS said `RegStore GET found AoR: "sip:536c9a191d7819ce5434878cpvbl3@domain"`. However, looking in the Sprout logs, this AoR data structure was 12 bytes long and contained no bindings, so this is a pretty misleading log.

In this case, the fact that we had no bindings was at odds with the Homestead response, which said the subscriber was registered (due to the bug fixed by https://github.com/Metaswitch/sprout/commit/072fcd9008bb1bc4302e60f4ad6a4853b7b28d38). It would be nice to have a log explicitly flagging this mismatch.

**Comment by eleanor-merry** [comment]
Fixed by #916
