### ISSUE TITLE
OPTIONS polls are logged to SAS but can't be searched for

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#677]
OPTIONS polls are logged to SAS but have no markers on them (so can't be found).

This is because they are logged by stack.cpp but markers are added by the module that handles them - the options-handling module doesn't add any markers.

It's not clear whether the right fix is to add markers in the options-handling module or to change stack.cpp not to log OPTIONS messages at all - they don't add much value.

**Comment by rkd-msw** [comment]
Fixed by #1075.
