### ISSUE TITLE
AIO nodes allow too much disk space for logs

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/sprout#806]
Each log type (`sprout_*`, `access_*`, `homestead_*`...) has 1Gb of disk space allocated to it in the cleanup cron jobs.  Sadly, there are 7 of these and there's only ~2.5Gb of spare disk space on the AIO node (which has an 8Gb disk).

When the disk fills up, bad things happen (100% wait, Cassandra can't come up/crashes, SSH access is lost, kittens mew piteously etc.)

**Comment by graemerobertson** [comment]
As per the discussion in https://github.com/Metaswitch/homestead/pull/197, we now have a max_log_directory_size config option on Clearwater nodes. We should integrate this with Chef for AIO nodes.

**Comment by graemerobertson** [comment]
Given that we think all we can do here is to set max_log_directory_size to something sensible for AIO nodes in Chef, and I assume that's trivial, I'm adding the easy tag.

**Comment by graemerobertson** [comment]
Also, @rkd-msw, unless you're fixing this, do you want to unclaim it?
