### ISSUE TITLE
Invalid XML in Registration Event Package

### ISSUE THREAD

**Issue by alankwon** [Metaswitch/sprout#828]
When I SUBSCRIBE to the registration event package, Sprout is returning the following XML in the SIP NOTIFY body:

```
<?xml version="1.0" encoding="UTF-8"?>
<reginfo xmlns="urn:ietf:params:xml:ns:reginfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0" state="partial">  
<registration aor="sip:+15554443004@xxxx.xxx.com" id="12335157013393702988" state="active">
  <contact id="<urn:gsma:imei:35513605-240951-6>:1" state="active" Event="refreshed">
   <uri>sip:+15554443004@xxx.xx.xx.xx:39861;transport=TCP;ob</uri>
  </contact>
</registration>
</reginfo>
```

Couple of problems with the XML:

1.  <contact id> contains data with < >, which is invalid syntax. Should be replaced with &lt; and &gt;  
2.  In the same <contact id> element, the tag Event is capitalized. It should be "event" according to RFC 3680.

**Comment by eleanor-merry** [comment]
Closing this, as the issue to fix up escaping is covered by #749
