### ISSUE TITLE
Message loop when no routes found

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#870]
During GR testing I found two cases where sprout can get into a messaging loop:

1. When trying to get the I-CSCF to use SRV records - _sip._tcp.sprout.example.com – I managed to make sprout loop on a REGISTER. The cause was a misconfiguration, in that I had homestead configured to return a URL containing port 5054 for the S-CSCF (which causes sprout not to do a SRV look up), but I had no DNS A records for sprout.example.com, so when sprout looked up that domain name it got zero (0) entries which resulted in it looping back on itself until I cancelled the registration from the phone.
2. Similarly, if all entries in SRV _sip._tcp.sprout.example.com get blacklisted (can’t explain how that happened, but it did), sprout ends up with zero entries which resulted in it looping back on itself until monit restarted it.

**Comment by rkd-msw** [comment]
@dtheobald - have you seen this issue recently, and if so, do you have SAS traces?

**Comment by JimBunch** [comment]
Marked as critical because Sprout starts looping until monit restarts it which is call processing service affecting.

**Comment by dtheobald** [comment]
I haven't seen this recently, so I'm closing it.
