### ISSUE TITLE
Can’t add the /etc/clearwater/remote_cluster_settings file without restarting sprout

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#871]
You can’t add the /etc/clearwater/remote_cluster_settings file without restarting sprout (i.e. reload won’t work because there was no /etc/clearwater/remote_cluster_settings file when I first started sprout. Granted the use case for this is quite rare, that being that this would only be a problem when converting a non-GR system to a GR system. However, for completeness, perhaps an empty ‘remote_cluster_settings’ file should be installed by default.

**Comment by rkd-msw** [comment]
Fixed by the above PR.
