### ISSUE TITLE
Missing ENT log for memcached read alarm

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#902]
Error - ```Error memcachedstore.cpp:516: Failed to read data for reg\\sip:5165191003@mvoip.richlab.datcon.co.uk from 2 replicas``` - should produce an ENT log indicating which replicas (IP address/port) failed.

**Comment by eleanor-merry** [comment]
Overriden as part of https://github.com/Metaswitch/cpp-common/pull/441
