### ISSUE TITLE
Sprout doesn't handle SIP URIs with parameters embedded in the username

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#914]
My TAS was sending SIP requests with a request URI of the form `sip:1234567890;cic=0001@example.com;user=phone`.

Unfortunately, Sprout did not parse this correctly, and ended up (after ENUM processing), deciding that this was `12345678900001` (i.e considering the carrier ID to be part of the DN).

I managed to reconfigure the TAS I was working with, but this might causes interop issues with others.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/937
