### ISSUE TITLE
Sprout's logs aren't clear when ENUM is not being performed

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#915]
While investigating #914, it took me a while to realize that ENUM lookups weren't being performed because neither DNS- nor file-based ENUM had been configured.  It would be really useful to have a log (SAS and trace) saying that we're not doing ENUM lookups and that we're instead jumping straight to BGCF.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/937
