### ISSUE TITLE
Sprout congestion causes unnecessary location lookups to Homestead, and the generation of malformed ACR info to Ralf

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#921]
While running a heavy traffic load, Sprout-1 was restarted by Monit due to a heartbeat error. Sprout-2 then became overloaded and started to respond with 503s. The call flows looked fine until ACKs sent from terminating S-CSCFs to originating S-CSCFs started looping. This lead to unexpected location requests to Homestead and malformed ACRs (no ccf data) to Ralf.

**Comment by JimBunch** [comment]
Marked as critical since it affects the accuracy of the billing.

**Comment by graemerobertson** [comment]
This is a duplicate of https://github.com/Metaswitch/sprout/issues/1091
