### ISSUE TITLE
Sprout RegStore deserialization isn't very robust

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#922]
AoRs retrieved from from the RegStore are parsed by the `desetrialize_aor` method. This uses a string stream to extract sections of the data and uses them to fill in an AoR object. 

The code doesn't do any checking that data it extracts is correct. Crucially it does not check for EOF on the string stream, so if the record is corrupt the AoR is filled in based on uninitialized memory.

**Comment by rkd-msw** [comment]
@AlexHockey , does https://github.com/Metaswitch/sprout/commit/06ebe58708158be8029ca0cc1181645169d5b7e0 and/or the fact we now default to JSON, mean this is fixed?

**Comment by AlexHockey** [comment]
There is still a very small amount of value in fixing this bug. We haven't yet shipped a release that writes the new JSON format (meaning there are plenty of binary records still around), and our downstream projects might not cut over to JSON straight away. However the benefit seems fairly small so I'm happy to close this.
