### ISSUE TITLE
Chrome can't cope with URI-encoded usernames in TURN URIs

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#93]
Chrome 25 doesn't cope with URI-encoded usernames in TURN URIs - it treats them literally (i.e., including %40 instead of @) which means it responds incorrectly to the auth challenge.

This is tracked by https://code.google.com/p/webrtc/issues/detail?id=1508.

We've implemented a work-around in restund, but should back it out once the Chrome issue is fixed.

**Comment by rkd-msw** [comment]
Marking all restund issues as low-priority.

**Comment by rkd-msw** [comment]
Closing based on @mirw's doc update at https://github.com/Metaswitch/clearwater-readthedocs/pull/178.
