### ISSUE TITLE
It's odd that almost all sproutlets are bound to the `scscf` port

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#957]
If I deploy Sprout providing Gemini or Memento services, they are exposed on the port defined by the `scscf` parameter in `/etc/clearwater/config`.

Not sure what we should do - rename the parameter or introduce a new parameter for each AS?

**Comment by mirw** [comment]
Likewise, it's a little bit odd that the hostname for a Gemini-only node is stored in `sprout_hostname` or `sprout_hostname_mgmt`.

**Comment by bossmc** [comment]
This feels like sproutlet-specific configuration (which we don't currently have support for).  To consider when we next revisit out configuration model.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/sprout/pull/1364
