### ISSUE TITLE
Sprout's stdout goes to /dev/null

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#965]
Issue #963 covers a crash in which glibc detects memory corruption and dumps details to stdout.  Unfortunately, sprout's stdout is redirected to /dev/null, so there's no way to see these details.

We should redirect this output elsewhere and gather it as part of diagnostics dumps.

**Comment by richardwhiuk** [comment]
Sprout's error and info logs are redirected by Utils::daemonize in cpp-common.

So we need to provide a path for stderr and stdout in src/main.cpp, and then add parameters to cpp-common to use them.

**Comment by mirw** [comment]
Just assigned the pull requests back to you.
