### ISSUE TITLE
Several issues with ENT logs

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#973]
I was running stress against a Clearwater deployment.  I had some misconfiguration so that

*   on one of my nodes, Chronos wasn't running
*   my Homer node wasn't provisioned with any subscribers.

I got lots of log spam with logs like the following.

```
Mar 11 15:46:56 ip-10-138-17-172 REG[32496]: 1005 - Description: http://10.138.17.172:7253/timers failed to communicate with HTTP server 10.138.17.172 with curl error Couldn't connect to server code 7. @@Cause: An HTTP connection attempt failed to the specified server with the specified error code. @@Effect: This condition impacts the ability to register, subscribe, or make a call. @@Action: (1). Check to see if the specified host has failed. (2). Check to see if there is TCP connectivity to the host by using ping and/or Wireshark.
Mar 11 15:50:06 ip-10-138-17-172 /9TC3mlqt7[3743]: 1005 - Description: http://homer.example.com:7888/org.etsi.ngn.simservs/users/sip%3A2010050005%40example.com/simservs.xml failed to communicate with HTTP server 10.138.6.114 with curl error No error code 0. @@Cause: An HTTP connection attempt failed to the specified server with the specified error code. @@Effect: This condition impacts the ability to register, subscribe, or make a call. @@Action: (1). Check to see if the specified host has failed. (2). Check to see if there is TCP connectivity to the host by using ping and/or Wireshark.
```

There are several issues here.

*   There's log spam.  We really shouldn't generate a log on every single request.
*   The description refers to "curl".  Does the administrator know what that is?
*   The second log says "with curl error No error code 0".  It turns out that this was because we had an HTTP error code 404.  The log should make this clear.
*   What does "http:... failed to communicate with HTTP server" actually mean?  Why would a URL be communicating with an HTTP server?
*   The effect is wrong.  I was running stress and did not actually see any failures.  (Presumably call services weren't being applied, and I didn't have deregistration notifications being sent.)
*   The process in the second log is `/9TC3mlqt7`.  Surely that's wrong?

Raising as one issue because these all seem to be in a similar area.

**Comment by rkd-msw** [comment]
Should we simply be removing CL_DIAMETER_ROUTE_ERR and CL_HTTP_COMM_ERR from https://github.com/Metaswitch/cpp-common/blob/master/include/cpp_common_pd_definitions.h? I think both of them could only be hit on the call path - so they will inherently cause log spam, and you'd be able to debug from SAS logs (and if you don't have SAS, I suspect you'd be debugging from engineering logs at debug level rather than ENT logs).

**Comment by mirw** [comment]
The last bullet (about the process being wrong) is due to the following lines.

```
  boost::filesystem::path p = argv[0];
  openlog(p.filename().c_str(), PDLOG_PID, PDLOG_LOCAL6);
```

p.filename().c_str() falls out of scope almost immediately.  Changing this to something like the following would fix it.

```
  boost::filesystem::path p = argv[0];
  // Copy the filename to a string so that we can be sure of its lifespan -
  // the value passed to openlog must be valid for the duration of the program.
  std::string filename = p.filename().c_str();
  openlog(filename.c_str(), PDLOG_PID, PDLOG_LOCAL6);
```

**Comment by rkd-msw** [comment]
Reopening - that fix was only partial.

**Comment by mirw** [comment]
I've coded a fix for the wording issue.  The only remaining issue is the log spam, which is covered by https://github.com/Metaswitch/cpp-common/issues/317.

**Comment by mirw** [comment]
All issues except https://github.com/Metaswitch/cpp-common/issues/317 are now fixed - closing.
