### ISSUE TITLE
Misleading SAS log when wrong password used

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#983]
I configured a phone to register with the wrong password and saw the following misleading log.

    Authentication failed as the downstream node didn't return an authentication vector

I think this is log `0x810042` aka `AUTHENTICATION_FAILED`.  `AUTHENTICATION_FAILED` is used in 2 places in `authentication.cpp` and I think we instead need 2 separate logs.

**Comment by eleanor-merry** [comment]
Duplicate of https://github.com/Metaswitch/clearwater-sas-resources/issues/49?

**Comment by mirw** [comment]
Good spot.  Closing as duplicate.
