### ISSUE TITLE
Calls result in 483 (too many hops) when terminating leg is not registered and call routes through a VoLTE TAS

### ISSUE THREAD

**Issue by bobgithub07** [Metaswitch/sprout#997]

**Comment by tcaterisano** [comment]
This issue is preventing some MMTEL tests from passing.  This was not an issue until we upgraded to the most recent release.

**Comment by mirw** [comment]
The initial request is routed to `sprout.mvoip....` but once originating processing completes, we pick an S-CSCF to handle the terminating calls and get back `sprout.vm3....`.  Both `sprout.mvoip....` and `sprout.vm3....` resolve to the same IP addresses: 192.168.162.108, 192.168.162.97 and 192.168.162.98.

However, the Sprout nodes only know their identity as `sprout.movip...` not as `sprout.vm3...`, so they simply forward on requests that they receive for `sprout.vm3....` (cyclically, in this case).

It looks like maybe you renamed your deployment from `sprout.vm3....` to `sprout.mvoip....` and haven't fixed up the `/etc/clearwater/scscf.json` file at the same time.  Please can you check?

**Comment by tcaterisano** [comment]
s-cscf.json file was updated and issue is resolved. Thanks,
